/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2018 Hex_27
 * Copyright (c) 2021 Crypto Morin
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
 * PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
 * FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package top.brmc.devlib.remain;

import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import top.brmc.devlib.CommonCore;
import top.brmc.devlib.ItemUtil;
import top.brmc.devlib.MinecraftVersion;
import top.brmc.devlib.MinecraftVersion.V;
import top.brmc.devlib.ReflectionUtil;
import top.brmc.devlib.ValidCore;

import lombok.Getter;
import lombok.NonNull;

/**
 * <b>CompMaterial</b> - 数据值/扁平化之前<br>
 * 优先以 1.13 及以上版本为准。
 * <p>
 * 此类主要用于支持 {@link ItemStack}。如果你想将其用于方块，则需要使用
 * <a href="https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/XBlock.java">XBlock</a>
 * <p>
 * 扁平化之前：https://minecraft.wiki/w/Java_Edition_data_values/Pre-flattening
 * 材质：https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
 * 材质（1.12）：https://helpch.at/docs/1.12.2/index.html?org/bukkit/Material.html
 * 材质 ID：https://minecraft-ids.grahamedgecombe.com/
 * 材质源代码：https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/Material.java
 * XMaterial v1：https://www.spigotmc.org/threads/329630/
 * <p>
 * 如果有人尝试使用数据值无效的物品，此类会抛出 "unsupported material" 错误；这只会发生在 1.12 及以下的服务器上，或者
 * 本工具缺少该特定版本中的某个新材质时。
 * 要获取无效物品（即 <a href="https://minecraft.wiki/w/Missing_textures_and_models#Missing_texture">Missing Texture Block</a>），你可以使用命令
 * <b>/give @p minecraft:dirt 1 10</b>，其中 1 为物品数量，10 为数据值。数据值为 {@code 10} 的材质 {@link #DIRT} 并不存在。
 *
 * @author Crypto Morin, forked by kangarko from MineAcademy.org
 */
public enum CompMaterial {
	ACACIA_BOAT("BOAT_ACACIA"),
	ACACIA_BUTTON("WOOD_BUTTON"),
	ACACIA_CHEST_BOAT,
	ACACIA_DOOR("ACACIA_DOOR", "ACACIA_DOOR_ITEM"),
	ACACIA_FENCE,
	ACACIA_FENCE_GATE,
	ACACIA_HANGING_SIGN,
	ACACIA_LEAVES(0, "LEAVES_2"),
	ACACIA_LOG(0, "LOG_2"),
	ACACIA_PLANKS(4, "WOOD"),
	ACACIA_PRESSURE_PLATE("WOOD_PLATE"),
	ACACIA_SAPLING(4, "SAPLING"),
	ACACIA_SIGN("SIGN_POST", "SIGN"),
	ACACIA_SLAB(4, "WOOD_DOUBLE_STEP", "WOOD_STEP", "WOODEN_SLAB"),
	ACACIA_STAIRS,
	ACACIA_TRAPDOOR("TRAP_DOOR"),
	ACACIA_WALL_HANGING_SIGN,
	ACACIA_WALL_SIGN("WALL_SIGN"),
	ACACIA_WOOD(0, "LOG_2"),
	ACTIVATOR_RAIL,
	/**
	 * <a href="https://minecraft.wiki/w/Air">空气</a>
	 * {@link Material#isAir()}
	 *
	 * @see #VOID_AIR
	 * @see #CAVE_AIR
	 */
	AIR,
	ALLAY_SPAWN_EGG,
	ALLIUM(2, "RED_ROSE"),
	AMETHYST_BLOCK,
	AMETHYST_CLUSTER,
	AMETHYST_SHARD,
	ANCIENT_DEBRIS,
	ANDESITE(5, "STONE"),
	ANDESITE_SLAB,
	ANDESITE_STAIRS,
	ANDESITE_WALL,
	ANGLER_POTTERY_SHERD,
	ANVIL,
	APPLE,
	ARCHER_POTTERY_SHERD,
	ARMADILLO_SCUTE,
	ARMADILLO_SPAWN_EGG,
	ARMOR_STAND,
	ARMS_UP_POTTERY_SHERD,
	ARROW,
	ATTACHED_MELON_STEM(7, "MELON_STEM"),
	ATTACHED_PUMPKIN_STEM(7, "PUMPKIN_STEM"),
	AXOLOTL_BUCKET,
	AXOLOTL_SPAWN_EGG,
	AZALEA,
	AZALEA_LEAVES,
	AZURE_BLUET(3, "RED_ROSE"),
	BAKED_POTATO,
	BAMBOO,
	BAMBOO_BLOCK,
	BAMBOO_BUTTON,
	BAMBOO_CHEST_RAFT,
	BAMBOO_DOOR,
	BAMBOO_FENCE,
	BAMBOO_FENCE_GATE,
	BAMBOO_HANGING_SIGN,
	BAMBOO_MOSAIC,
	BAMBOO_MOSAIC_SLAB,
	BAMBOO_MOSAIC_STAIRS,
	BAMBOO_PLANKS,
	BAMBOO_PRESSURE_PLATE,
	BAMBOO_RAFT,
	BAMBOO_SAPLING,
	BAMBOO_SIGN,
	BAMBOO_SLAB,
	BAMBOO_STAIRS,
	BAMBOO_TRAPDOOR,
	BAMBOO_WALL_HANGING_SIGN,
	BAMBOO_WALL_SIGN,
	BARREL,
	BARRIER,
	BASALT,
	BAT_SPAWN_EGG(65, "MONSTER_EGG"),
	BEACON,
	BEDROCK,
	BEEF("RAW_BEEF"),
	BEEHIVE,
	/**
	 * 甜菜根在 1.13 之前是已知材质
	 */
	BEETROOT("BEETROOT_BLOCK"),
	BEETROOTS("BEETROOT"),
	BEETROOT_SEEDS,
	BEETROOT_SOUP,
	BEE_NEST,
	BEE_SPAWN_EGG,
	BELL,
	BIG_DRIPLEAF,
	BIG_DRIPLEAF_STEM,
	BIRCH_BOAT("BOAT_BIRCH"),
	BIRCH_BUTTON("WOOD_BUTTON"),
	BIRCH_CHEST_BOAT,
	BIRCH_DOOR("BIRCH_DOOR", "BIRCH_DOOR_ITEM"),
	BIRCH_FENCE,
	BIRCH_FENCE_GATE,
	BIRCH_HANGING_SIGN,
	BIRCH_LEAVES(2, "LEAVES"),
	BIRCH_LOG(2, "LOG"),
	BIRCH_PLANKS(2, "WOOD"),
	BIRCH_PRESSURE_PLATE("WOOD_PLATE"),
	BIRCH_SAPLING(2, "SAPLING"),
	BIRCH_SIGN("SIGN_POST", "SIGN"),
	BIRCH_SLAB(2, "WOOD_DOUBLE_STEP", "WOOD_STEP", "WOODEN_SLAB"),
	BIRCH_STAIRS("BIRCH_WOOD_STAIRS"),
	BIRCH_TRAPDOOR("TRAP_DOOR"),
	BIRCH_WALL_HANGING_SIGN,
	BIRCH_WALL_SIGN("WALL_SIGN"),
	BIRCH_WOOD(2, "LOG"),
	BLACKSTONE,
	BLACKSTONE_SLAB,
	BLACKSTONE_STAIRS,
	BLACKSTONE_WALL,
	BLACK_BANNER("STANDING_BANNER", "BANNER"),
	/**
	 * 由于枚举按字母排序，1.12+ 会将 "BED" 解释为 BLACK_BED。
	 */
	BLACK_BED(supports(12) ? 15 : 0, "BED_BLOCK", "BED"),
	BLACK_CANDLE,
	BLACK_CANDLE_CAKE,
	BLACK_CARPET(15, "CARPET"),
	BLACK_CONCRETE(15, "CONCRETE"),
	BLACK_CONCRETE_POWDER(15, "CONCRETE_POWDER"),
	BLACK_DYE,
	BLACK_GLAZED_TERRACOTTA,
	BLACK_SHULKER_BOX,
	BLACK_STAINED_GLASS(15, "STAINED_GLASS"),
	BLACK_STAINED_GLASS_PANE(15, "STAINED_GLASS_PANE"),
	BLACK_TERRACOTTA(15, "STAINED_CLAY"),
	BLACK_WALL_BANNER("WALL_BANNER"),
	BLACK_WOOL(15, "WOOL"),
	BLADE_POTTERY_SHERD,
	BLAST_FURNACE,
	BLAZE_POWDER,
	BLAZE_ROD,
	BLAZE_SPAWN_EGG(61, "MONSTER_EGG"),
	BLUE_BANNER(4, "STANDING_BANNER", "BANNER"),
	BLUE_BED(supports(12) ? 11 : 0, "BED_BLOCK", "BED"),
	BLUE_CANDLE,
	BLUE_CANDLE_CAKE,
	BLUE_CARPET(11, "CARPET"),
	BLUE_CONCRETE(11, "CONCRETE"),
	BLUE_CONCRETE_POWDER(11, "CONCRETE_POWDER"),
	BLUE_DYE(4, "INK_SACK", "LAPIS_LAZULI"),
	BLUE_EGG,
	BLUE_GLAZED_TERRACOTTA,
	BLUE_ICE,
	BLUE_ORCHID(1, "RED_ROSE"),
	BLUE_SHULKER_BOX,
	BLUE_STAINED_GLASS(11, "STAINED_GLASS"),
	BLUE_STAINED_GLASS_PANE(11, "THIN_GLASS", "STAINED_GLASS_PANE"),
	BLUE_TERRACOTTA(11, "STAINED_CLAY"),
	BLUE_WALL_BANNER(4, "WALL_BANNER"),
	BLUE_WOOL(11, "WOOL"),
	BOGGED_SPAWN_EGG,
	BOLT_ARMOR_TRIM_SMITHING_TEMPLATE,
	BONE,
	BONE_BLOCK,
	BONE_MEAL(15, "INK_SACK"),
	BOOK,
	BOOKSHELF,
	BOW,
	BOWL,
	BRAIN_CORAL,
	BRAIN_CORAL_BLOCK,
	BRAIN_CORAL_FAN,
	BRAIN_CORAL_WALL_FAN,
	BREAD,
	BREEZE_ROD,
	BREEZE_SPAWN_EGG,
	BREWER_POTTERY_SHERD,
	BREWING_STAND("BREWING_STAND", "BREWING_STAND_ITEM"),
	BRICK("CLAY_BRICK"),
	BRICKS("BRICK"),
	BRICK_SLAB(4, "STEP"),
	BRICK_STAIRS,
	BRICK_WALL,
	BROWN_BANNER(3, "STANDING_BANNER", "BANNER"),
	BROWN_BED(supports(12) ? 12 : 0, "BED_BLOCK", "BED"),
	BROWN_CANDLE,
	BROWN_CANDLE_CAKE,
	BROWN_CARPET(12, "CARPET"),
	BROWN_CONCRETE(12, "CONCRETE"),
	BROWN_CONCRETE_POWDER(12, "CONCRETE_POWDER"),
	BROWN_DYE(3, "INK_SACK", "DYE", "COCOA_BEANS"),
	BROWN_EGG,
	BROWN_GLAZED_TERRACOTTA,
	BROWN_MUSHROOM,
	BROWN_MUSHROOM_BLOCK("BROWN_MUSHROOM", "HUGE_MUSHROOM_1"),
	BROWN_SHULKER_BOX,
	BROWN_STAINED_GLASS(12, "STAINED_GLASS"),
	BROWN_STAINED_GLASS_PANE(12, "THIN_GLASS", "STAINED_GLASS_PANE"),
	BROWN_TERRACOTTA(12, "STAINED_CLAY"),
	BROWN_WALL_BANNER(3, "WALL_BANNER"),
	BROWN_WOOL(12, "WOOL"),
	BRUSH,
	BUBBLE_COLUMN,
	BUBBLE_CORAL,
	BUBBLE_CORAL_BLOCK,
	BUBBLE_CORAL_FAN,
	BUBBLE_CORAL_WALL_FAN,
	BUCKET,
	BUDDING_AMETHYST,
	BUNDLE,
	BURN_POTTERY_SHERD,
	BUSH,
	CACTUS,
	CACTUS_FLOWER,
	CAKE("CAKE_BLOCK"),
	CALCITE,
	CALIBRATED_SCULK_SENSOR,
	CAMEL_SPAWN_EGG,
	CAMPFIRE,
	CANDLE,
	CANDLE_CAKE,
	CARROT("CARROT_ITEM"),
	CARROTS("CARROT"),
	CARROT_ON_A_STICK("CARROT_STICK"),
	CARTOGRAPHY_TABLE,
	CARVED_PUMPKIN,
	CAT_SPAWN_EGG,
	CAULDRON("CAULDRON", "CAULDRON_ITEM"),
	/**
	 * 未添加 1.13 标签，因为它与 {@link #AIR} 是同一个东西
	 *
	 * @see #VOID_AIR
	 */
	CAVE_AIR("AIR"),
	CAVE_SPIDER_SPAWN_EGG(59, "MONSTER_EGG"),
	CAVE_VINES,
	CAVE_VINES_PLANT,
	IRON_CHAIN("CHAIN"),
	CHAINMAIL_BOOTS,
	CHAINMAIL_CHESTPLATE,
	CHAINMAIL_HELMET,
	CHAINMAIL_LEGGINGS,
	CHAIN_COMMAND_BLOCK("COMMAND", "COMMAND_CHAIN"),
	CHARCOAL(1, "COAL"),
	CHERRY_BOAT,
	CHERRY_BUTTON,
	CHERRY_CHEST_BOAT,
	CHERRY_DOOR,
	CHERRY_FENCE,
	CHERRY_FENCE_GATE,
	CHERRY_HANGING_SIGN,
	CHERRY_LEAVES,
	CHERRY_LOG,
	CHERRY_PLANKS,
	CHERRY_PRESSURE_PLATE,
	CHERRY_SAPLING,
	CHERRY_SIGN,
	CHERRY_SLAB,
	CHERRY_STAIRS,
	CHERRY_TRAPDOOR,
	CHERRY_WALL_HANGING_SIGN,
	CHERRY_WALL_SIGN,
	CHERRY_WOOD,
	CHEST("LOCKED_CHEST"),
	CHEST_MINECART("STORAGE_MINECART"),
	CHICKEN("RAW_CHICKEN"),
	CHICKEN_SPAWN_EGG(93, "MONSTER_EGG"),
	CHIPPED_ANVIL(1, "ANVIL"),
	CHISELED_BOOKSHELF,
	CHISELED_COPPER,
	CHISELED_DEEPSLATE,
	CHISELED_NETHER_BRICKS(1, "NETHER_BRICKS"),
	CHISELED_POLISHED_BLACKSTONE("POLISHED_BLACKSTONE"),
	CHISELED_QUARTZ_BLOCK(1, "QUARTZ_BLOCK"),
	CHISELED_RED_SANDSTONE(1, "RED_SANDSTONE"),
	CHISELED_SANDSTONE(1, "SANDSTONE"),
	CHISELED_STONE_BRICKS(3, "SMOOTH_BRICK"),
	CHISELED_TUFF,
	CHISELED_TUFF_BRICKS,
	CHORUS_FLOWER,
	CHORUS_FRUIT,
	CHORUS_PLANT,
	CLAY,
	CLAY_BALL,
	CLOCK("WATCH"),
	COAL,
	COAL_BLOCK,
	COAL_ORE,
	COARSE_DIRT(1, "DIRT"),
	COAST_ARMOR_TRIM_SMITHING_TEMPLATE,
	COBBLED_DEEPSLATE,
	COBBLED_DEEPSLATE_SLAB,
	COBBLED_DEEPSLATE_STAIRS,
	COBBLED_DEEPSLATE_WALL,
	COBBLESTONE,
	COBBLESTONE_SLAB(3, "STEP"),
	COBBLESTONE_STAIRS,
	COBBLESTONE_WALL("COBBLE_WALL"),
	COBWEB("WEB"),
	COCOA,
	COCOA_BEANS(3, "INK_SACK"),
	COD("RAW_FISH"),
	COD_BUCKET,
	COD_SPAWN_EGG,
	COMMAND_BLOCK("COMMAND"),
	COMMAND_BLOCK_MINECART("COMMAND_MINECART"),
	/**
	 * 与红石火把和红石灯不同……REDTONE_COMPARATOR_OFF 和 REDSTONE_COMPARATOR_ON
	 * 都不是物品。REDSTONE_COMPARATOR 才是。
	 *
	 * @see #REDSTONE_TORCH
	 * @see #REDSTONE_LAMP
	 */
	COMPARATOR("REDSTONE_COMPARATOR_OFF", "REDSTONE_COMPARATOR_ON", "REDSTONE_COMPARATOR"),
	COMPASS,
	COMPOSTER,
	CONDUIT,
	COOKED_BEEF,
	COOKED_CHICKEN,
	COOKED_COD("COOKED_FISH"),
	COOKED_MUTTON,
	COOKED_PORKCHOP("GRILLED_PORK"),
	COOKED_RABBIT,
	COOKED_SALMON(1, "COOKED_FISH"),
	COOKIE,
	COPPER_BLOCK,
	COPPER_BULB,
	COPPER_DOOR,
	COPPER_GRATE,
	COPPER_INGOT,
	COPPER_ORE,
	COPPER_TRAPDOOR,
	CORNFLOWER,
	COW_SPAWN_EGG(92, "MONSTER_EGG"),
	CRACKED_DEEPSLATE_BRICKS,
	CRACKED_DEEPSLATE_TILES,
	CRACKED_NETHER_BRICKS(2, "NETHER_BRICKS"),
	CRACKED_POLISHED_BLACKSTONE_BRICKS("POLISHED_BLACKSTONE_BRICKS"),
	CRACKED_STONE_BRICKS(2, "SMOOTH_BRICK"),
	CRAFTER,
	CRAFTING_TABLE("WORKBENCH"),
	CREEPER_BANNER_PATTERN,
	CREEPER_HEAD(4, "SKULL", "SKULL_ITEM"),
	CREEPER_SPAWN_EGG(50, "MONSTER_EGG"),
	CREEPER_WALL_HEAD(4, "SKULL", "SKULL_ITEM"),
	CRIMSON_BUTTON,
	CRIMSON_DOOR,
	CRIMSON_FENCE,
	CRIMSON_FENCE_GATE,
	CRIMSON_FUNGUS,
	CRIMSON_HANGING_SIGN,
	CRIMSON_HYPHAE,
	CRIMSON_NYLIUM,
	CRIMSON_PLANKS,
	CRIMSON_PRESSURE_PLATE,
	CRIMSON_ROOTS,
	CRIMSON_SIGN("SIGN_POST"),
	CRIMSON_SLAB,
	CRIMSON_STAIRS,
	CRIMSON_STEM,
	CRIMSON_TRAPDOOR,
	CRIMSON_WALL_HANGING_SIGN,
	CRIMSON_WALL_SIGN("WALL_SIGN"),
	CROSSBOW,
	CRYING_OBSIDIAN,
	CUT_COPPER,
	CUT_COPPER_SLAB,
	CUT_COPPER_STAIRS,
	CUT_RED_SANDSTONE,
	CUT_RED_SANDSTONE_SLAB("STONE_SLAB2"),
	CUT_SANDSTONE,
	CUT_SANDSTONE_SLAB(1, "STEP"),
	CYAN_BANNER(6, "STANDING_BANNER", "BANNER"),
	CYAN_BED(supports(12) ? 9 : 0, "BED_BLOCK", "BED"),
	CYAN_CANDLE,
	CYAN_CANDLE_CAKE,
	CYAN_CARPET(9, "CARPET"),
	CYAN_CONCRETE(9, "CONCRETE"),
	CYAN_CONCRETE_POWDER(9, "CONCRETE_POWDER"),
	CYAN_DYE(6, "INK_SACK"),
	CYAN_GLAZED_TERRACOTTA,
	CYAN_SHULKER_BOX,
	CYAN_STAINED_GLASS(9, "STAINED_GLASS"),
	CYAN_STAINED_GLASS_PANE(9, "STAINED_GLASS_PANE"),
	CYAN_TERRACOTTA(9, "STAINED_CLAY"),
	CYAN_WALL_BANNER(6, "WALL_BANNER"),
	CYAN_WOOL(9, "WOOL"),
	DAMAGED_ANVIL(2, "ANVIL"),
	DANDELION("YELLOW_FLOWER"),
	DANGER_POTTERY_SHERD,
	DARK_OAK_BOAT("BOAT_DARK_OAK"),
	DARK_OAK_BUTTON("WOOD_BUTTON"),
	DARK_OAK_CHEST_BOAT,
	DARK_OAK_DOOR("DARK_OAK_DOOR", "DARK_OAK_DOOR_ITEM"),
	DARK_OAK_FENCE,
	DARK_OAK_FENCE_GATE,
	DARK_OAK_HANGING_SIGN,
	DARK_OAK_LEAVES(1, "LEAVES_2"),
	DARK_OAK_LOG(1, "LOG_2"),
	DARK_OAK_PLANKS(5, "WOOD"),
	DARK_OAK_PRESSURE_PLATE("WOOD_PLATE"),
	DARK_OAK_SAPLING(5, "SAPLING"),
	DARK_OAK_SIGN("SIGN_POST", "SIGN"),
	DARK_OAK_SLAB(5, "WOOD_DOUBLE_STEP", "WOOD_STEP", "WOODEN_SLAB"),
	DARK_OAK_STAIRS,
	DARK_OAK_TRAPDOOR("TRAP_DOOR"),
	DARK_OAK_WALL_HANGING_SIGN,
	DARK_OAK_WALL_SIGN("WALL_SIGN"),
	DARK_OAK_WOOD(1, "LOG_2"),
	DARK_PRISMARINE(2, "PRISMARINE"),
	DARK_PRISMARINE_SLAB,
	DARK_PRISMARINE_STAIRS,
	DAYLIGHT_DETECTOR("DAYLIGHT_DETECTOR_INVERTED"),
	DEAD_BRAIN_CORAL,
	DEAD_BRAIN_CORAL_BLOCK,
	DEAD_BRAIN_CORAL_FAN,
	DEAD_BRAIN_CORAL_WALL_FAN,
	DEAD_BUBBLE_CORAL,
	DEAD_BUBBLE_CORAL_BLOCK,
	DEAD_BUBBLE_CORAL_FAN,
	DEAD_BUBBLE_CORAL_WALL_FAN,
	DEAD_BUSH("LONG_GRASS"),
	DEAD_FIRE_CORAL,
	DEAD_FIRE_CORAL_BLOCK,
	DEAD_FIRE_CORAL_FAN,
	DEAD_FIRE_CORAL_WALL_FAN,
	DEAD_HORN_CORAL,
	DEAD_HORN_CORAL_BLOCK,
	DEAD_HORN_CORAL_FAN,
	DEAD_HORN_CORAL_WALL_FAN,
	DEAD_TUBE_CORAL,
	DEAD_TUBE_CORAL_BLOCK,
	DEAD_TUBE_CORAL_FAN,
	DEAD_TUBE_CORAL_WALL_FAN,
	DEBUG_STICK,
	DECORATED_POT,
	DEEPSLATE,
	DEEPSLATE_BRICKS,
	DEEPSLATE_BRICK_SLAB,
	DEEPSLATE_BRICK_STAIRS,
	DEEPSLATE_BRICK_WALL,
	DEEPSLATE_COAL_ORE,
	DEEPSLATE_COPPER_ORE,
	DEEPSLATE_DIAMOND_ORE,
	DEEPSLATE_EMERALD_ORE,
	DEEPSLATE_GOLD_ORE,
	DEEPSLATE_IRON_ORE,
	DEEPSLATE_LAPIS_ORE,
	DEEPSLATE_REDSTONE_ORE,
	DEEPSLATE_TILES,
	DEEPSLATE_TILE_SLAB,
	DEEPSLATE_TILE_STAIRS,
	DEEPSLATE_TILE_WALL,
	DETECTOR_RAIL,
	DIAMOND,
	DIAMOND_AXE,
	DIAMOND_BLOCK,
	DIAMOND_BOOTS,
	DIAMOND_CHESTPLATE,
	DIAMOND_HELMET,
	DIAMOND_HOE,
	DIAMOND_HORSE_ARMOR("DIAMOND_BARDING"),
	DIAMOND_LEGGINGS,
	DIAMOND_ORE,
	DIAMOND_PICKAXE,
	DIAMOND_SHOVEL("DIAMOND_SPADE"),
	DIAMOND_SWORD,
	DIORITE(3, "STONE"),
	DIORITE_SLAB,
	DIORITE_STAIRS,
	DIORITE_WALL,
	DIRT,
	/**
	 * 在 1.17 中更改
	 */
	DIRT_PATH("GRASS_PATH"),
	DISC_FRAGMENT_5,
	DISPENSER,
	DOLPHIN_SPAWN_EGG,
	DONKEY_SPAWN_EGG(32, "MONSTER_EGG"),
	DRAGON_BREATH("DRAGONS_BREATH"),
	DRAGON_EGG,
	DRAGON_HEAD(5, "SKULL", "SKULL_ITEM"),
	DRAGON_WALL_HEAD(5, "SKULL", "SKULL_ITEM"),
	DRIED_KELP,
	DRIED_KELP_BLOCK,
	DRIPSTONE_BLOCK,
	DROPPER,
	DROWNED_SPAWN_EGG,
	DUNE_ARMOR_TRIM_SMITHING_TEMPLATE,
	ECHO_SHARD,
	EGG,
	ELDER_GUARDIAN_SPAWN_EGG(4, "MONSTER_EGG"),
	ELYTRA,
	EMERALD,
	EMERALD_BLOCK,
	EMERALD_ORE,
	ENCHANTED_BOOK,
	ENCHANTED_GOLDEN_APPLE(1, "GOLDEN_APPLE"),
	ENCHANTING_TABLE("ENCHANTMENT_TABLE"),
	ENDERMAN_SPAWN_EGG(58, "MONSTER_EGG"),
	ENDERMITE_SPAWN_EGG(67, "MONSTER_EGG"),
	ENDER_CHEST,
	ENDER_DRAGON_SPAWN_EGG,
	ENDER_EYE("EYE_OF_ENDER"),
	ENDER_PEARL,
	END_CRYSTAL,
	END_GATEWAY,
	END_PORTAL("ENDER_PORTAL"),
	END_PORTAL_FRAME("ENDER_PORTAL_FRAME"),
	END_ROD,
	END_STONE("ENDER_STONE"),
	END_STONE_BRICKS("END_BRICKS"),
	END_STONE_BRICK_SLAB,
	END_STONE_BRICK_STAIRS,
	END_STONE_BRICK_WALL,
	EVOKER_SPAWN_EGG(34, "MONSTER_EGG"),
	EXPERIENCE_BOTTLE("EXP_BOTTLE"),
	EXPLORER_POTTERY_SHERD,
	EXPOSED_CHISELED_COPPER,
	EXPOSED_COPPER,
	EXPOSED_COPPER_BULB,
	EXPOSED_COPPER_DOOR,
	EXPOSED_COPPER_GRATE,
	EXPOSED_COPPER_TRAPDOOR,
	EXPOSED_CUT_COPPER,
	EXPOSED_CUT_COPPER_SLAB,
	EXPOSED_CUT_COPPER_STAIRS,
	EYE_ARMOR_TRIM_SMITHING_TEMPLATE,
	FARMLAND("SOIL"),
	FEATHER,
	FERMENTED_SPIDER_EYE,
	FERN(2, "LONG_GRASS"),
	/**
	 * 出于某种原因，已填充的地图物品非常特殊。
	 * 它们的数据值从 0 开始，玩家每
	 * 创建一张新地图，该地图的数据值就会增加。
	 * <a href="https://github.com/CryptoMorin/XSeries/issues/91">GitHub Issue</a>
	 */
	FILLED_MAP("MAP"),
	FIRE,
	FIREFLY_BUSH,
	FIREWORK_ROCKET("FIREWORK"),
	FIREWORK_STAR("FIREWORK_CHARGE"),
	FIRE_CHARGE("FIREBALL"),
	FIRE_CORAL,
	FIRE_CORAL_BLOCK,
	FIRE_CORAL_FAN,
	FIRE_CORAL_WALL_FAN,
	FISHING_ROD,
	FLETCHING_TABLE,
	FLINT,
	FLINT_AND_STEEL,
	FLOWERING_AZALEA,
	FLOWERING_AZALEA_LEAVES,
	FLOWER_BANNER_PATTERN,
	FLOWER_POT("FLOWER_POT", "FLOWER_POT_ITEM"),
	FLOW_ARMOR_TRIM_SMITHING_TEMPLATE,
	FLOW_BANNER_PATTERN,
	FLOW_POTTERY_SHERD,
	FOX_SPAWN_EGG,
	FRIEND_POTTERY_SHERD,
	FROGSPAWN,
	FROG_SPAWN_EGG,
	/**
	 * 这种特殊材质无法作为物品获得。
	 */
	FROSTED_ICE,
	FURNACE("BURNING_FURNACE"),
	FURNACE_MINECART("POWERED_MINECART"),
	GHAST_SPAWN_EGG(56, "MONSTER_EGG"),
	GHAST_TEAR,
	GILDED_BLACKSTONE,
	GLASS,
	GLASS_BOTTLE,
	GLASS_PANE("THIN_GLASS"),
	GLISTERING_MELON_SLICE("SPECKLED_MELON"),
	GLOBE_BANNER_PATTERN,
	GLOWSTONE,
	GLOWSTONE_DUST,
	GLOW_BERRIES,
	GLOW_INK_SAC,
	GLOW_ITEM_FRAME,
	GLOW_LICHEN,
	GLOW_SQUID_SPAWN_EGG,
	GOAT_HORN,
	GOAT_SPAWN_EGG,
	GOLDEN_APPLE,
	GOLDEN_AXE("GOLD_AXE"),
	GOLDEN_BOOTS("GOLD_BOOTS"),
	GOLDEN_CARROT,
	GOLDEN_DANDELION,
	GOLDEN_CHESTPLATE("GOLD_CHESTPLATE"),
	GOLDEN_HELMET("GOLD_HELMET"),
	GOLDEN_HOE("GOLD_HOE"),
	GOLDEN_HORSE_ARMOR("GOLD_BARDING"),
	GOLDEN_LEGGINGS("GOLD_LEGGINGS"),
	GOLDEN_PICKAXE("GOLD_PICKAXE"),
	GOLDEN_SHOVEL("GOLD_SPADE"),
	GOLDEN_SWORD("GOLD_SWORD"),
	GOLD_BLOCK,
	GOLD_INGOT,
	GOLD_NUGGET,
	GOLD_ORE,
	GRANITE(1, "STONE"),
	GRANITE_SLAB,
	GRANITE_STAIRS,
	GRANITE_WALL,
	GRASS_BLOCK("GRASS"),
	GRAVEL,
	GRAY_BANNER(8, "STANDING_BANNER", "BANNER"),
	GRAY_BED(supports(12) ? 7 : 0, "BED_BLOCK", "BED"),
	GRAY_CANDLE,
	GRAY_CANDLE_CAKE,
	GRAY_CARPET(7, "CARPET"),
	GRAY_CONCRETE(7, "CONCRETE"),
	GRAY_CONCRETE_POWDER(7, "CONCRETE_POWDER"),
	GRAY_DYE(8, "INK_SACK"),
	GRAY_GLAZED_TERRACOTTA,
	GRAY_SHULKER_BOX,
	GRAY_STAINED_GLASS(7, "STAINED_GLASS"),
	GRAY_STAINED_GLASS_PANE(7, "THIN_GLASS", "STAINED_GLASS_PANE"),
	GRAY_TERRACOTTA(7, "STAINED_CLAY"),
	GRAY_WALL_BANNER(8, "WALL_BANNER"),
	GRAY_WOOL(7, "WOOL"),
	GREEN_BANNER(2, "STANDING_BANNER", "BANNER"),
	GREEN_BED(supports(12) ? 13 : 0, "BED_BLOCK", "BED"),
	GREEN_CANDLE,
	GREEN_CANDLE_CAKE,
	GREEN_CARPET(13, "CARPET"),
	GREEN_CONCRETE(13, "CONCRETE"),
	GREEN_CONCRETE_POWDER(13, "CONCRETE_POWDER"),
	/**
	 * 1.13 重命名为 CACTUS_GREEN
	 * 1.14 重命名为 GREEN_DYE
	 */
	GREEN_DYE(2, "INK_SACK", "CACTUS_GREEN"),
	GREEN_GLAZED_TERRACOTTA,
	GREEN_SHULKER_BOX,
	GREEN_STAINED_GLASS(13, "STAINED_GLASS"),
	GREEN_STAINED_GLASS_PANE(13, "THIN_GLASS", "STAINED_GLASS_PANE"),
	GREEN_TERRACOTTA(13, "STAINED_CLAY"),
	GREEN_WALL_BANNER(2, "WALL_BANNER"),
	GREEN_WOOL(13, "WOOL"),
	GRINDSTONE,
	GUARDIAN_SPAWN_EGG(68, "MONSTER_EGG"),
	GUNPOWDER("SULPHUR"),
	GUSTER_BANNER_PATTERN,
	GUSTER_POTTERY_SHERD,
	HANGING_ROOTS,
	HAY_BLOCK,
	HEARTBREAK_POTTERY_SHERD,
	HEART_OF_THE_SEA,
	HEART_POTTERY_SHERD,
	HEAVY_CORE,
	HEAVY_WEIGHTED_PRESSURE_PLATE("IRON_PLATE"),
	HOGLIN_SPAWN_EGG("MONSTER_EGG"),
	HONEYCOMB,
	HONEYCOMB_BLOCK,
	HONEY_BLOCK,
	HONEY_BOTTLE,
	HOPPER,
	HOPPER_MINECART,
	HORN_CORAL,
	HORN_CORAL_BLOCK,
	HORN_CORAL_FAN,
	HORN_CORAL_WALL_FAN,
	HORSE_SPAWN_EGG(100, "MONSTER_EGG"),
	HOST_ARMOR_TRIM_SMITHING_TEMPLATE,
	HOWL_POTTERY_SHERD,
	HUSK_SPAWN_EGG(23, "MONSTER_EGG"),
	ICE,
	INFESTED_CHISELED_STONE_BRICKS(5, "MONSTER_EGGS"),
	INFESTED_COBBLESTONE(1, "MONSTER_EGGS"),
	INFESTED_CRACKED_STONE_BRICKS(4, "MONSTER_EGGS"),
	INFESTED_DEEPSLATE,
	INFESTED_MOSSY_STONE_BRICKS(3, "MONSTER_EGGS"),
	INFESTED_STONE("MONSTER_EGGS"),
	INFESTED_STONE_BRICKS(2, "MONSTER_EGGS"),
	/**
	 * 我们只为 {@link #BLACK_DYE} 添加 "INK_SAC"，因为它是
	 * （与此材质相关联的材质中）唯一在 1.13 之后
	 * 添加的材质，这意味着它可以同时使用 INK_SACK 和 INK_SAC。
	 */
	INK_SAC("INK_SACK"),
	IRON_AXE,
	IRON_BARS("IRON_FENCE"),
	IRON_BLOCK,
	IRON_BOOTS,
	IRON_CHESTPLATE,
	IRON_DOOR("IRON_DOOR_BLOCK"),
	IRON_GOLEM_SPAWN_EGG,
	IRON_HELMET,
	IRON_HOE,
	IRON_HORSE_ARMOR("IRON_BARDING"),
	IRON_INGOT,
	IRON_LEGGINGS,
	IRON_NUGGET,
	IRON_ORE,
	IRON_PICKAXE,
	IRON_SHOVEL("IRON_SPADE"),
	IRON_SWORD,
	IRON_TRAPDOOR,
	ITEM_FRAME,
	JACK_O_LANTERN,
	JIGSAW,
	JUKEBOX,
	JUNGLE_BOAT("BOAT_JUNGLE"),
	JUNGLE_BUTTON("WOOD_BUTTON"),
	JUNGLE_CHEST_BOAT,
	JUNGLE_DOOR("JUNGLE_DOOR", "JUNGLE_DOOR_ITEM"),
	JUNGLE_FENCE,
	JUNGLE_FENCE_GATE,
	JUNGLE_HANGING_SIGN,
	JUNGLE_LEAVES(3, "LEAVES"),
	JUNGLE_LOG(3, "LOG"),
	JUNGLE_PLANKS(3, "WOOD"),
	JUNGLE_PRESSURE_PLATE("WOOD_PLATE"),
	JUNGLE_SAPLING(3, "SAPLING"),
	JUNGLE_SIGN("SIGN_POST", "SIGN"),
	JUNGLE_SLAB(3, "WOOD_DOUBLE_STEP", "WOOD_STEP", "WOODEN_SLAB"),
	JUNGLE_STAIRS("JUNGLE_WOOD_STAIRS"),
	JUNGLE_TRAPDOOR("TRAP_DOOR"),
	JUNGLE_WALL_HANGING_SIGN,
	JUNGLE_WALL_SIGN("WALL_SIGN"),
	JUNGLE_WOOD(3, "LOG"),
	KELP,
	KELP_PLANT,
	KNOWLEDGE_BOOK("BOOK"),
	LADDER,
	LANTERN,
	LAPIS_BLOCK,
	LAPIS_LAZULI(4, "INK_SACK"),
	LAPIS_ORE,
	LARGE_AMETHYST_BUD,
	LARGE_FERN(3, "DOUBLE_PLANT"),
	LAVA("STATIONARY_LAVA"),
	LAVA_BUCKET,
	LAVA_CAULDRON,
	LEAD("LEASH"),
	LEAF_LITTER,
	LEATHER,
	LEATHER_BOOTS,
	LEATHER_CHESTPLATE,
	LEATHER_HELMET,
	LEATHER_HORSE_ARMOR("IRON_HORSE_ARMOR"),
	LEATHER_LEGGINGS,
	LECTERN,
	LEVER,
	LIGHT,
	LIGHTNING_ROD,
	LIGHT_BLUE_BANNER(12, "STANDING_BANNER", "BANNER"),
	LIGHT_BLUE_BED(supports(12) ? 3 : 0, "BED_BLOCK", "BED"),
	LIGHT_BLUE_CANDLE,
	LIGHT_BLUE_CANDLE_CAKE,
	LIGHT_BLUE_CARPET(3, "CARPET"),
	LIGHT_BLUE_CONCRETE(3, "CONCRETE"),
	LIGHT_BLUE_CONCRETE_POWDER(3, "CONCRETE_POWDER"),
	LIGHT_BLUE_DYE(12, "INK_SACK"),
	LIGHT_BLUE_GLAZED_TERRACOTTA,
	LIGHT_BLUE_SHULKER_BOX,
	LIGHT_BLUE_STAINED_GLASS(3, "STAINED_GLASS"),
	LIGHT_BLUE_STAINED_GLASS_PANE(3, "THIN_GLASS", "STAINED_GLASS_PANE"),
	LIGHT_BLUE_TERRACOTTA(3, "STAINED_CLAY"),
	LIGHT_BLUE_WALL_BANNER(12, "WALL_BANNER", "STANDING_BANNER", "BANNER"),
	LIGHT_BLUE_WOOL(3, "WOOL"),
	LIGHT_GRAY_BANNER(7, "STANDING_BANNER", "BANNER"),
	LIGHT_GRAY_BED(supports(12) ? 8 : 0, "BED_BLOCK", "BED"),
	LIGHT_GRAY_CANDLE,
	LIGHT_GRAY_CANDLE_CAKE,
	LIGHT_GRAY_CARPET(8, "CARPET"),
	LIGHT_GRAY_CONCRETE(8, "CONCRETE"),
	LIGHT_GRAY_CONCRETE_POWDER(8, "CONCRETE_POWDER"),
	LIGHT_GRAY_DYE(7, "INK_SACK"),
	/**
	 * 1.12 中重命名为 SILVER_GLAZED_TERRACOTTA
	 * 1.14 中重命名为 LIGHT_GRAY_GLAZED_TERRACOTTA
	 */
	LIGHT_GRAY_GLAZED_TERRACOTTA("SILVER_GLAZED_TERRACOTTA"),
	LIGHT_GRAY_SHULKER_BOX("SILVER_SHULKER_BOX"),
	LIGHT_GRAY_STAINED_GLASS(8, "STAINED_GLASS"),
	LIGHT_GRAY_STAINED_GLASS_PANE(8, "THIN_GLASS", "STAINED_GLASS_PANE"),
	LIGHT_GRAY_TERRACOTTA(8, "STAINED_CLAY"),
	LIGHT_GRAY_WALL_BANNER(7, "WALL_BANNER"),
	LIGHT_GRAY_WOOL(8, "WOOL"),
	LIGHT_WEIGHTED_PRESSURE_PLATE("GOLD_PLATE"),
	LILAC(1, "DOUBLE_PLANT"),
	LILY_OF_THE_VALLEY,
	LILY_PAD("WATER_LILY"),
	LIME_BANNER(10, "STANDING_BANNER", "BANNER"),
	LIME_BED(supports(12) ? 5 : 0, "BED_BLOCK", "BED"),
	LIME_CANDLE,
	LIME_CANDLE_CAKE,
	LIME_CARPET(5, "CARPET"),
	LIME_CONCRETE(5, "CONCRETE"),
	LIME_CONCRETE_POWDER(5, "CONCRETE_POWDER"),
	LIME_DYE(10, "INK_SACK"),
	LIME_GLAZED_TERRACOTTA,
	LIME_SHULKER_BOX,
	LIME_STAINED_GLASS(5, "STAINED_GLASS"),
	LIME_STAINED_GLASS_PANE(5, "STAINED_GLASS_PANE"),
	LIME_TERRACOTTA(5, "STAINED_CLAY"),
	LIME_WALL_BANNER(10, "WALL_BANNER"),
	LIME_WOOL(5, "WOOL"),
	LINGERING_POTION,
	LLAMA_SPAWN_EGG(103, "MONSTER_EGG"),
	LODESTONE,
	LOOM,
	MACE,
	MAGENTA_BANNER(13, "STANDING_BANNER", "BANNER"),
	MAGENTA_BED(supports(12) ? 2 : 0, "BED_BLOCK", "BED"),
	MAGENTA_CANDLE,
	MAGENTA_CANDLE_CAKE,
	MAGENTA_CARPET(2, "CARPET"),
	MAGENTA_CONCRETE(2, "CONCRETE"),
	MAGENTA_CONCRETE_POWDER(2, "CONCRETE_POWDER"),
	MAGENTA_DYE(13, "INK_SACK"),
	MAGENTA_GLAZED_TERRACOTTA,
	MAGENTA_SHULKER_BOX,
	MAGENTA_STAINED_GLASS(2, "STAINED_GLASS"),
	MAGENTA_STAINED_GLASS_PANE(2, "THIN_GLASS", "STAINED_GLASS_PANE"),
	MAGENTA_TERRACOTTA(2, "STAINED_CLAY"),
	MAGENTA_WALL_BANNER(13, "WALL_BANNER"),
	MAGENTA_WOOL(2, "WOOL"),
	MAGMA_BLOCK("MAGMA"),
	MAGMA_CREAM,
	MAGMA_CUBE_SPAWN_EGG(62, "MONSTER_EGG"),
	MANGROVE_BOAT,
	MANGROVE_BUTTON,
	MANGROVE_CHEST_BOAT,
	MANGROVE_DOOR,
	MANGROVE_FENCE,
	MANGROVE_FENCE_GATE,
	MANGROVE_HANGING_SIGN,
	MANGROVE_LEAVES,
	MANGROVE_LOG,
	MANGROVE_PLANKS,
	MANGROVE_PRESSURE_PLATE,
	MANGROVE_PROPAGULE,
	MANGROVE_ROOTS,
	MANGROVE_SIGN,
	MANGROVE_SLAB,
	MANGROVE_STAIRS,
	MANGROVE_TRAPDOOR,
	MANGROVE_WALL_HANGING_SIGN,
	MANGROVE_WALL_SIGN,
	MANGROVE_WOOD,
	/**
	 * 将其加入重复列表会在 1.13+ 版本中得到已填充的地图，
	 * 而将其从重复列表中移除，在 -1.12 版本中
	 * 仍会得到已填充的地图。
	 * 由于更高版本是我们的优先目标，在想出修复办法之前
	 * 我会保留对 1.13+ 的支持。
	 */
	MAP("EMPTY_MAP"),
	MEDIUM_AMETHYST_BUD,
	MELON("MELON_BLOCK"),
	MELON_SEEDS,
	MELON_SLICE("MELON"),
	MELON_STEM,
	MILK_BUCKET,
	MINECART,
	MINER_POTTERY_SHERD,
	MOJANG_BANNER_PATTERN,
	MOOSHROOM_SPAWN_EGG(96, "MONSTER_EGG"),
	MOSSY_COBBLESTONE,
	MOSSY_COBBLESTONE_SLAB(),
	MOSSY_COBBLESTONE_STAIRS,
	MOSSY_COBBLESTONE_WALL(1, "COBBLE_WALL", "COBBLESTONE_WALL"),
	MOSSY_STONE_BRICKS(1, "SMOOTH_BRICK"),
	MOSSY_STONE_BRICK_SLAB,
	MOSSY_STONE_BRICK_STAIRS,
	MOSSY_STONE_BRICK_WALL,
	MOSS_BLOCK,
	MOSS_CARPET,
	MOURNER_POTTERY_SHERD,
	MOVING_PISTON("PISTON_MOVING_PIECE"),
	MUD,
	MUDDY_MANGROVE_ROOTS,
	MUD_BRICKS,
	MUD_BRICK_SLAB,
	MUD_BRICK_STAIRS,
	MUD_BRICK_WALL,
	MULE_SPAWN_EGG(32, "MONSTER_EGG"),
	MUSHROOM_STEM("BROWN_MUSHROOM"),
	MUSHROOM_STEW("MUSHROOM_SOUP"),
	MUSIC_DISC_11("RECORD_11"),
	MUSIC_DISC_13("GOLD_RECORD"),
	MUSIC_DISC_5,
	MUSIC_DISC_BLOCKS("RECORD_3"),
	MUSIC_DISC_CAT("GREEN_RECORD"),
	MUSIC_DISC_CHIRP("RECORD_4"),
	MUSIC_DISC_CREATOR,
	MUSIC_DISC_CREATOR_MUSIC_BOX,
	MUSIC_DISC_FAR("RECORD_5"),
	MUSIC_DISC_MALL("RECORD_6"),
	MUSIC_DISC_MELLOHI("RECORD_7"),
	MUSIC_DISC_OTHERSIDE,
	MUSIC_DISC_PIGSTEP,
	MUSIC_DISC_PRECIPICE,
	MUSIC_DISC_RELIC,
	MUSIC_DISC_STAL("RECORD_8"),
	MUSIC_DISC_STRAD("RECORD_9"),
	MUSIC_DISC_WAIT("RECORD_12"),
	MUSIC_DISC_WARD("RECORD_10"),
	MUTTON,
	MYCELIUM("MYCEL"),
	NAME_TAG,
	NAUTILUS_SHELL,
	NETHERITE_AXE,
	NETHERITE_BLOCK,
	NETHERITE_BOOTS,
	NETHERITE_CHESTPLATE,
	NETHERITE_HELMET,
	NETHERITE_HOE,
	NETHERITE_INGOT,
	NETHERITE_LEGGINGS,
	NETHERITE_PICKAXE,
	NETHERITE_SCRAP,
	NETHERITE_SHOVEL,
	NETHERITE_SWORD,
	NETHERITE_UPGRADE_SMITHING_TEMPLATE,
	NETHERRACK,
	NETHER_BRICK("NETHER_BRICK_ITEM"),
	NETHER_BRICKS("NETHER_BRICK"),
	NETHER_BRICK_FENCE("NETHER_FENCE"),
	NETHER_BRICK_SLAB(6, "STEP"),
	NETHER_BRICK_STAIRS,
	NETHER_BRICK_WALL,
	NETHER_GOLD_ORE,
	NETHER_PORTAL("PORTAL"),
	NETHER_QUARTZ_ORE("QUARTZ_ORE"),
	NETHER_SPROUTS,
	NETHER_STAR,
	/**
	 * 正如 <a href="https://minecraft.wiki/w/Nether_Wart">Nether Wart</a> 中所述，
	 * 下界疣在代码中也被称为 nether stalk。
	 * NETHER_STALK 是下界疣的种植状态。
	 */
	NETHER_WART("NETHER_WARTS", "NETHER_STALK"),
	NETHER_WART_BLOCK,
	NOTE_BLOCK,
	OAK_BOAT("BOAT"),
	OAK_BUTTON("WOOD_BUTTON"),
	OAK_CHEST_BOAT,
	OAK_DOOR("WOODEN_DOOR", "WOOD_DOOR"),
	OAK_FENCE("FENCE"),
	OAK_FENCE_GATE("FENCE_GATE"),
	OAK_HANGING_SIGN,
	OAK_LEAVES("LEAVES"),
	OAK_LOG("LOG"),
	OAK_PLANKS("WOOD"),
	OAK_PRESSURE_PLATE("WOOD_PLATE"),
	OAK_SAPLING("SAPLING"),
	OAK_SIGN("SIGN_POST", "SIGN"),
	OAK_SLAB("WOOD_DOUBLE_STEP", "WOOD_STEP", "WOODEN_SLAB"),
	OAK_STAIRS("WOOD_STAIRS"),
	OAK_TRAPDOOR("TRAP_DOOR"),
	OAK_WALL_HANGING_SIGN,
	OAK_WALL_SIGN("WALL_SIGN"),
	OAK_WOOD("LOG"),
	OBSERVER,
	OBSIDIAN,
	OCELOT_SPAWN_EGG(98, "MONSTER_EGG"),
	OCHRE_FROGLIGHT,
	OMINOUS_BOTTLE,
	OMINOUS_TRIAL_KEY,
	ORANGE_BANNER(14, "STANDING_BANNER", "BANNER"),
	ORANGE_BED(supports(12) ? 1 : 0, "BED_BLOCK", "BED"),
	ORANGE_CANDLE,
	ORANGE_CANDLE_CAKE,
	ORANGE_CARPET(1, "CARPET"),
	ORANGE_CONCRETE(1, "CONCRETE"),
	ORANGE_CONCRETE_POWDER(1, "CONCRETE_POWDER"),
	ORANGE_DYE(14, "INK_SACK"),
	ORANGE_GLAZED_TERRACOTTA,
	ORANGE_SHULKER_BOX,
	ORANGE_STAINED_GLASS(1, "STAINED_GLASS"),
	ORANGE_STAINED_GLASS_PANE(1, "STAINED_GLASS_PANE"),
	ORANGE_TERRACOTTA(1, "STAINED_CLAY"),
	ORANGE_TULIP(5, "RED_ROSE"),
	ORANGE_WALL_BANNER(14, "WALL_BANNER"),
	ORANGE_WOOL(1, "WOOL"),
	OXEYE_DAISY(8, "RED_ROSE"),
	OXIDIZED_CHISELED_COPPER,
	OXIDIZED_COPPER,
	OXIDIZED_COPPER_BULB,
	OXIDIZED_COPPER_DOOR,
	OXIDIZED_COPPER_GRATE,
	OXIDIZED_COPPER_TRAPDOOR,
	OXIDIZED_CUT_COPPER,
	OXIDIZED_CUT_COPPER_SLAB,
	OXIDIZED_CUT_COPPER_STAIRS,
	PACKED_ICE,
	PACKED_MUD,
	PAINTING,
	PANDA_SPAWN_EGG,
	PAPER,
	PARROT_SPAWN_EGG(105, "MONSTER_EGG"),
	PEARLESCENT_FROGLIGHT,
	PEONY(5, "DOUBLE_PLANT"),
	PETRIFIED_OAK_SLAB("WOOD_STEP"),
	PHANTOM_MEMBRANE,
	PHANTOM_SPAWN_EGG,
	PIGLIN_BANNER_PATTERN,
	PIGLIN_BRUTE_SPAWN_EGG,
	PIGLIN_HEAD,
	PIGLIN_SPAWN_EGG(57, "MONSTER_EGG"),
	PIGLIN_WALL_HEAD,
	PIG_SPAWN_EGG(90, "MONSTER_EGG"),
	PILLAGER_SPAWN_EGG,
	PINK_BANNER(9, "STANDING_BANNER", "BANNER"),
	PINK_BED(supports(12) ? 6 : 0, "BED_BLOCK", "BED"),
	PINK_CANDLE,
	PINK_CANDLE_CAKE,
	PINK_CARPET(6, "CARPET"),
	PINK_CONCRETE(6, "CONCRETE"),
	PINK_CONCRETE_POWDER(6, "CONCRETE_POWDER"),
	PINK_DYE(9, "INK_SACK"),
	PINK_GLAZED_TERRACOTTA,
	PINK_PETALS,
	PINK_SHULKER_BOX,
	PINK_STAINED_GLASS(6, "STAINED_GLASS"),
	PINK_STAINED_GLASS_PANE(6, "THIN_GLASS", "STAINED_GLASS_PANE"),
	PINK_TERRACOTTA(6, "STAINED_CLAY"),
	PINK_TULIP(7, "RED_ROSE"),
	PINK_WALL_BANNER(9, "WALL_BANNER"),
	PINK_WOOL(6, "WOOL"),
	PISTON("PISTON_BASE"),
	PISTON_HEAD("PISTON_EXTENSION"),
	PITCHER_CROP,
	PITCHER_PLANT,
	PITCHER_POD,
	PLAYER_HEAD(3, "SKULL", "SKULL_ITEM"),
	PLAYER_WALL_HEAD(3, "SKULL", "SKULL_ITEM"),
	PLENTY_POTTERY_SHERD,
	PODZOL(2, "DIRT"),
	POINTED_DRIPSTONE,
	POISONOUS_POTATO,
	POLAR_BEAR_SPAWN_EGG(102, "MONSTER_EGG"),
	POLISHED_ANDESITE(6, "STONE"),
	POLISHED_ANDESITE_SLAB,
	POLISHED_ANDESITE_STAIRS,
	POLISHED_BASALT,
	POLISHED_BLACKSTONE,
	POLISHED_BLACKSTONE_BRICKS,
	POLISHED_BLACKSTONE_BRICK_SLAB,
	POLISHED_BLACKSTONE_BRICK_STAIRS,
	POLISHED_BLACKSTONE_BRICK_WALL,
	POLISHED_BLACKSTONE_BUTTON,
	POLISHED_BLACKSTONE_PRESSURE_PLATE,
	POLISHED_BLACKSTONE_SLAB,
	POLISHED_BLACKSTONE_STAIRS,
	POLISHED_BLACKSTONE_WALL,
	POLISHED_DEEPSLATE,
	POLISHED_DEEPSLATE_SLAB,
	POLISHED_DEEPSLATE_STAIRS,
	POLISHED_DEEPSLATE_WALL,
	POLISHED_DIORITE(4, "STONE"),
	POLISHED_DIORITE_SLAB,
	POLISHED_DIORITE_STAIRS,
	POLISHED_GRANITE(2, "STONE"),
	POLISHED_GRANITE_SLAB,
	POLISHED_GRANITE_STAIRS,
	POLISHED_TUFF,
	POLISHED_TUFF_SLAB,
	POLISHED_TUFF_STAIRS,
	POLISHED_TUFF_WALL,
	POPPED_CHORUS_FRUIT("CHORUS_FRUIT_POPPED"),
	POPPY("RED_ROSE"),
	PORKCHOP("PORK"),
	POTATO("POTATO_ITEM"),
	POTATOES("POTATO"),
	POTION,
	POTTED_ACACIA_SAPLING(4, "FLOWER_POT"),
	POTTED_ALLIUM(2, "FLOWER_POT"),
	POTTED_AZALEA_BUSH,
	POTTED_AZURE_BLUET(3, "FLOWER_POT"),
	POTTED_BAMBOO,
	POTTED_BIRCH_SAPLING(2, "FLOWER_POT"),
	POTTED_BLUE_ORCHID(1, "FLOWER_POT"),
	POTTED_BROWN_MUSHROOM("FLOWER_POT"),
	POTTED_CACTUS("FLOWER_POT"),
	POTTED_CHERRY_SAPLING,
	POTTED_CORNFLOWER,
	POTTED_CRIMSON_FUNGUS,
	POTTED_CRIMSON_ROOTS,
	POTTED_DANDELION("FLOWER_POT"),
	POTTED_GOLDEN_DANDELION,
	POTTED_DARK_OAK_SAPLING(5, "FLOWER_POT"),
	POTTED_DEAD_BUSH("FLOWER_POT"),
	POTTED_FERN(2, "FLOWER_POT"),
	POTTED_FLOWERING_AZALEA_BUSH,
	POTTED_JUNGLE_SAPLING(3, "FLOWER_POT"),
	POTTED_LILY_OF_THE_VALLEY,
	POTTED_MANGROVE_PROPAGULE,
	POTTED_OAK_SAPLING("FLOWER_POT"),
	POTTED_ORANGE_TULIP(5, "FLOWER_POT"),
	POTTED_OXEYE_DAISY(8, "FLOWER_POT"),
	POTTED_PINK_TULIP(7, "FLOWER_POT"),
	POTTED_POPPY("FLOWER_POT"),
	POTTED_RED_MUSHROOM("FLOWER_POT"),
	POTTED_RED_TULIP(4, "FLOWER_POT"),
	POTTED_SPRUCE_SAPLING(1, "FLOWER_POT"),
	POTTED_TORCHFLOWER,
	POTTED_WARPED_FUNGUS,
	POTTED_WARPED_ROOTS,
	POTTED_WHITE_TULIP(6, "FLOWER_POT"),
	POTTED_WITHER_ROSE,
	POTTERY_SHARD_ARCHER,
	POTTERY_SHARD_ARMS_UP,
	POTTERY_SHARD_PRIZE,
	POTTERY_SHARD_SKULL,
	POWDER_SNOW,
	POWDER_SNOW_BUCKET,
	POWDER_SNOW_CAULDRON,
	POWERED_RAIL,
	PRISMARINE,
	PRISMARINE_BRICKS(1, "PRISMARINE"),
	PRISMARINE_BRICK_SLAB,
	PRISMARINE_BRICK_STAIRS,
	PRISMARINE_CRYSTALS,
	PRISMARINE_SHARD,
	PRISMARINE_SLAB,
	PRISMARINE_STAIRS,
	PRISMARINE_WALL,
	PRIZE_POTTERY_SHERD,
	PUFFERFISH(3, "RAW_FISH"),
	PUFFERFISH_BUCKET,
	PUFFERFISH_SPAWN_EGG,
	PUMPKIN,
	PUMPKIN_PIE,
	PUMPKIN_SEEDS,
	PUMPKIN_STEM,
	PURPLE_BANNER(5, "STANDING_BANNER", "BANNER"),
	PURPLE_BED(supports(12) ? 10 : 0, "BED_BLOCK", "BED"),
	PURPLE_CANDLE,
	PURPLE_CANDLE_CAKE,
	PURPLE_CARPET(10, "CARPET"),
	PURPLE_CONCRETE(10, "CONCRETE"),
	PURPLE_CONCRETE_POWDER(10, "CONCRETE_POWDER"),
	PURPLE_DYE(5, "INK_SACK"),
	PURPLE_GLAZED_TERRACOTTA,
	PURPLE_SHULKER_BOX,
	PURPLE_STAINED_GLASS(10, "STAINED_GLASS"),
	PURPLE_STAINED_GLASS_PANE(10, "THIN_GLASS", "STAINED_GLASS_PANE"),
	PURPLE_TERRACOTTA(10, "STAINED_CLAY"),
	PURPLE_WALL_BANNER(5, "WALL_BANNER"),
	PURPLE_WOOL(10, "WOOL"),
	PURPUR_BLOCK,
	PURPUR_PILLAR,
	PURPUR_SLAB("PURPUR_DOUBLE_SLAB"),
	PURPUR_STAIRS,
	QUARTZ,
	QUARTZ_BLOCK,
	QUARTZ_BRICKS,
	QUARTZ_PILLAR(2, "QUARTZ_BLOCK"),
	QUARTZ_SLAB(7, "STEP"),
	QUARTZ_STAIRS,
	RABBIT,
	RABBIT_FOOT,
	RABBIT_HIDE,
	RABBIT_SPAWN_EGG(101, "MONSTER_EGG"),
	RABBIT_STEW,
	RAIL("RAILS"),
	RAISER_ARMOR_TRIM_SMITHING_TEMPLATE,
	RAVAGER_SPAWN_EGG,
	RAW_COPPER,
	RAW_COPPER_BLOCK,
	RAW_GOLD,
	RAW_GOLD_BLOCK,
	RAW_IRON,
	RAW_IRON_BLOCK,
	RECOVERY_COMPASS,
	REDSTONE,
	REDSTONE_BLOCK,
	/**
	 * 与红石火把不同，REDSTONE_LAMP_ON 不是物品。
	 * 此名称放在列表中只是为了匹配。
	 *
	 * @see #REDSTONE_TORCH
	 */
	REDSTONE_LAMP("REDSTONE_LAMP_ON", "REDSTONE_LAMP_OFF"),
	REDSTONE_ORE("GLOWING_REDSTONE_ORE"),
	/**
	 * REDSTONE_TORCH_OFF 不是物品，而是方块。
	 * 但 REDSTONE_TORCH_ON 是物品。
	 * 此名称放在列表中只是为了匹配。
	 */
	REDSTONE_TORCH("REDSTONE_TORCH_OFF", "REDSTONE_TORCH_ON"),
	REDSTONE_WALL_TORCH,
	REDSTONE_WIRE,
	RED_BANNER(1, "STANDING_BANNER", "BANNER"),
	/**
	 * 数据值为 14 或 0
	 */
	RED_BED(supports(12) ? 14 : 0, "BED_BLOCK", "BED"),
	RED_CANDLE,
	RED_CANDLE_CAKE,
	RED_CARPET(14, "CARPET"),
	RED_CONCRETE(14, "CONCRETE"),
	RED_CONCRETE_POWDER(14, "CONCRETE_POWDER"),
	/**
	 * 1.13 重命名为 ROSE_RED
	 * 1.14 重命名为 RED_DYE
	 */
	RED_DYE(1, "INK_SACK", "ROSE_RED"),
	RED_GLAZED_TERRACOTTA,
	RED_MUSHROOM,
	RED_MUSHROOM_BLOCK("RED_MUSHROOM", "HUGE_MUSHROOM_2"),
	RED_NETHER_BRICKS("RED_NETHER_BRICK"),
	RED_NETHER_BRICK_SLAB,
	RED_NETHER_BRICK_STAIRS,
	RED_NETHER_BRICK_WALL,
	RED_SAND(1, "SAND"),
	RED_SANDSTONE,
	RED_SANDSTONE_SLAB("DOUBLE_STONE_SLAB2", "STONE_SLAB2"),
	RED_SANDSTONE_STAIRS,
	RED_SANDSTONE_WALL,
	RED_SHULKER_BOX,
	RED_STAINED_GLASS(14, "STAINED_GLASS"),
	RED_STAINED_GLASS_PANE(14, "THIN_GLASS", "STAINED_GLASS_PANE"),
	RED_TERRACOTTA(14, "STAINED_CLAY"),
	RED_TULIP(4, "RED_ROSE"),
	RED_WALL_BANNER(1, "WALL_BANNER"),
	RED_WOOL(14, "WOOL"),
	REINFORCED_DEEPSLATE,
	REPEATER("DIODE_BLOCK_ON", "DIODE_BLOCK_OFF", "DIODE"),
	REPEATING_COMMAND_BLOCK("COMMAND", "COMMAND_REPEATING"),
	RESPAWN_ANCHOR,
	RIB_ARMOR_TRIM_SMITHING_TEMPLATE,
	ROOTED_DIRT,
	ROSE_BUSH(4, "DOUBLE_PLANT"),
	ROTTEN_FLESH,
	SADDLE,
	SALMON(1, "RAW_FISH"),
	SALMON_BUCKET,
	SALMON_SPAWN_EGG,
	SAND,
	SANDSTONE,
	SANDSTONE_SLAB(1, "DOUBLE_STEP", "STEP", "STONE_SLAB"),
	SANDSTONE_STAIRS,
	SANDSTONE_WALL,
	SCAFFOLDING,
	SCRAPE_POTTERY_SHERD,
	SCULK,
	SCULK_CATALYST,
	SCULK_SENSOR,
	SCULK_SHRIEKER,
	SCULK_VEIN,
	SCUTE,
	SEAGRASS,
	SEA_LANTERN,
	SEA_PICKLE,
	SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE,
	SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE,
	SHEAF_POTTERY_SHERD,
	SHEARS,
	SHEEP_SPAWN_EGG(91, "MONSTER_EGG"),
	SHELTER_POTTERY_SHERD,
	SHIELD,
	SHORT_DRY_GRASS,
	/**
	 * 1.13.0：LONG_GRASS:1
	 * 1.20.4：GRASS -> SHORT_GRASS
	 */
	SHORT_GRASS(1, "GRASS", "LONG_GRASS"),
	SHROOMLIGHT,
	SHULKER_BOX("PURPLE_SHULKER_BOX"),
	SHULKER_SHELL,
	SHULKER_SPAWN_EGG(69, "MONSTER_EGG"),
	SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE,
	SILVERFISH_SPAWN_EGG(60, "MONSTER_EGG"),
	SKELETON_HORSE_SPAWN_EGG(28, "MONSTER_EGG"),
	SKELETON_SKULL("SKULL", "SKULL_ITEM"),
	SKELETON_SPAWN_EGG(51, "MONSTER_EGG"),
	SKELETON_WALL_SKULL("SKULL", "SKULL_ITEM"),
	SKULL_BANNER_PATTERN,
	SKULL_POTTERY_SHERD,
	SLIME_BALL,
	SLIME_BLOCK,
	SLIME_SPAWN_EGG(55, "MONSTER_EGG"),
	SMALL_AMETHYST_BUD,
	SMALL_DRIPLEAF,
	SMITHING_TABLE,
	SMOKER,
	SMOOTH_BASALT,
	SMOOTH_QUARTZ,
	SMOOTH_QUARTZ_SLAB,
	SMOOTH_QUARTZ_STAIRS,
	SMOOTH_RED_SANDSTONE(2, "RED_SANDSTONE"),
	SMOOTH_RED_SANDSTONE_SLAB("STONE_SLAB2"),
	SMOOTH_RED_SANDSTONE_STAIRS,
	SMOOTH_SANDSTONE(2, "SANDSTONE"),
	SMOOTH_SANDSTONE_SLAB,
	SMOOTH_SANDSTONE_STAIRS,
	SMOOTH_STONE,
	SMOOTH_STONE_SLAB,
	SNIFFER_EGG,
	SNIFFER_SPAWN_EGG,
	SNORT_POTTERY_SHERD,
	SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE,
	SNOW,
	SNOWBALL("SNOW_BALL"),
	SNOW_BLOCK,
	SNOW_GOLEM_SPAWN_EGG,
	SOUL_CAMPFIRE,
	SOUL_FIRE,
	SOUL_LANTERN,
	SOUL_SAND,
	SOUL_SOIL,
	SOUL_TORCH,
	SOUL_WALL_TORCH,
	SPAWNER("MOB_SPAWNER"),
	SPECTRAL_ARROW,
	SPIDER_EYE,
	SPIDER_SPAWN_EGG(52, "MONSTER_EGG"),
	SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE,
	SPLASH_POTION("POTION"),
	SPONGE,
	SPORE_BLOSSOM,
	SPRUCE_BOAT("BOAT_SPRUCE"),
	SPRUCE_BUTTON("WOOD_BUTTON"),
	SPRUCE_CHEST_BOAT,
	SPRUCE_DOOR("SPRUCE_DOOR", "SPRUCE_DOOR_ITEM"),
	SPRUCE_FENCE,
	SPRUCE_FENCE_GATE,
	SPRUCE_HANGING_SIGN,
	SPRUCE_LEAVES(1, "LEAVES"),
	SPRUCE_LOG(1, "LOG"),
	SPRUCE_PLANKS(1, "WOOD"),
	SPRUCE_PRESSURE_PLATE("WOOD_PLATE"),
	SPRUCE_SAPLING(1, "SAPLING"),
	SPRUCE_SIGN("SIGN_POST", "SIGN"),
	SPRUCE_SLAB(1, "WOOD_DOUBLE_STEP", "WOOD_STEP", "WOODEN_SLAB"),
	SPRUCE_STAIRS("SPRUCE_WOOD_STAIRS"),
	SPRUCE_TRAPDOOR("TRAP_DOOR"),
	SPRUCE_WALL_HANGING_SIGN,
	SPRUCE_WALL_SIGN("WALL_SIGN"),
	SPRUCE_WOOD(1, "LOG"),
	SPYGLASS,
	SQUID_SPAWN_EGG(94, "MONSTER_EGG"),
	STICK,
	STICKY_PISTON("PISTON_BASE", "PISTON_STICKY_BASE"),
	STONE,
	STONECUTTER,
	STONE_AXE,
	STONE_BRICKS("SMOOTH_BRICK"),
	STONE_BRICK_SLAB(5, "DOUBLE_STEP", "STEP", "STONE_SLAB"),
	STONE_BRICK_STAIRS("SMOOTH_STAIRS"),
	STONE_BRICK_WALL,
	STONE_BUTTON,
	STONE_HOE,
	STONE_PICKAXE,
	STONE_PRESSURE_PLATE("STONE_PLATE"),
	STONE_SHOVEL("STONE_SPADE"),
	STONE_SLAB("DOUBLE_STEP", "STEP"),
	STONE_STAIRS,
	STONE_SWORD,
	STRAY_SPAWN_EGG(6, "MONSTER_EGG"),
	STRIDER_SPAWN_EGG,
	STRING,
	STRIPPED_ACACIA_LOG,
	STRIPPED_ACACIA_WOOD,
	STRIPPED_BAMBOO_BLOCK,
	STRIPPED_BIRCH_LOG,
	STRIPPED_BIRCH_WOOD,
	STRIPPED_CHERRY_LOG,
	STRIPPED_CHERRY_WOOD,
	STRIPPED_CRIMSON_HYPHAE,
	STRIPPED_CRIMSON_STEM,
	STRIPPED_DARK_OAK_LOG,
	STRIPPED_DARK_OAK_WOOD,
	STRIPPED_JUNGLE_LOG,
	STRIPPED_JUNGLE_WOOD,
	STRIPPED_MANGROVE_LOG,
	STRIPPED_MANGROVE_WOOD,
	STRIPPED_OAK_LOG,
	STRIPPED_OAK_WOOD,
	STRIPPED_SPRUCE_LOG,
	STRIPPED_SPRUCE_WOOD,
	STRIPPED_WARPED_HYPHAE,
	STRIPPED_WARPED_STEM,
	STRUCTURE_BLOCK,
	/**
	 * 最初开发者使用屏障方块来实现此用途。
	 * 所以严格来说，这并不算是推荐使用的材质。
	 */
	STRUCTURE_VOID(10, "BARRIER"),
	SUGAR,
	/**
	 * 甘蔗在 1.13 之前是已知材质
	 */
	SUGAR_CANE("SUGAR_CANE_BLOCK"),
	SUNFLOWER("DOUBLE_PLANT"),
	SUSPICIOUS_GRAVEL,
	SUSPICIOUS_SAND,
	SUSPICIOUS_STEW,
	SWEET_BERRIES,
	SWEET_BERRY_BUSH,
	TADPOLE_BUCKET,
	TADPOLE_SPAWN_EGG,
	TALL_DRY_GRASS,
	TALL_GRASS(2, "DOUBLE_PLANT"),
	TALL_SEAGRASS,
	TARGET,
	TERRACOTTA("HARD_CLAY"),
	TEST_BLOCK,
	TEST_INSTANCE_BLOCK,
	TIDE_ARMOR_TRIM_SMITHING_TEMPLATE,
	TINTED_GLASS,
	TIPPED_ARROW,
	TNT,
	TNT_MINECART("EXPLOSIVE_MINECART"),
	TORCH,
	TORCHFLOWER,
	TORCHFLOWER_CROP,
	TORCHFLOWER_SEEDS,
	TOTEM_OF_UNDYING("TOTEM"),
	TRADER_LLAMA_SPAWN_EGG,
	TRAPPED_CHEST,
	TRIAL_KEY,
	TRIAL_SPAWNER,
	TRIDENT,
	TRIPWIRE,
	TRIPWIRE_HOOK,
	TROPICAL_FISH(2, "RAW_FISH"),
	TROPICAL_FISH_BUCKET("BUCKET", "WATER_BUCKET"),
	TROPICAL_FISH_SPAWN_EGG("MONSTER_EGG"),
	TUBE_CORAL,
	TUBE_CORAL_BLOCK,
	TUBE_CORAL_FAN,
	TUBE_CORAL_WALL_FAN,
	TUFF,
	TUFF_BRICKS,
	TUFF_BRICK_SLAB,
	TUFF_BRICK_STAIRS,
	TUFF_BRICK_WALL,
	TUFF_SLAB,
	TUFF_STAIRS,
	TUFF_WALL,
	TURTLE_EGG,
	TURTLE_HELMET,
	TURTLE_SCUTE,
	TURTLE_SPAWN_EGG,
	TWISTING_VINES,
	TWISTING_VINES_PLANT,
	VAULT,
	VERDANT_FROGLIGHT,
	VEX_ARMOR_TRIM_SMITHING_TEMPLATE,
	VEX_SPAWN_EGG(35, "MONSTER_EGG"),
	VILLAGER_SPAWN_EGG(120, "MONSTER_EGG"),
	VINDICATOR_SPAWN_EGG(36, "MONSTER_EGG"),
	VINE,
	/**
	 * 未添加 1.13 标签，因为它与 {@link #AIR} 是同一个东西
	 *
	 * @see #CAVE_AIR
	 */
	VOID_AIR("AIR"),
	WALL_TORCH("TORCH"),
	WANDERING_TRADER_SPAWN_EGG,
	WARDEN_SPAWN_EGG,
	WARD_ARMOR_TRIM_SMITHING_TEMPLATE,
	WARPED_BUTTON,
	WARPED_DOOR,
	WARPED_FENCE,
	WARPED_FENCE_GATE,
	WARPED_FUNGUS,
	WARPED_FUNGUS_ON_A_STICK,
	WARPED_HANGING_SIGN,
	WARPED_HYPHAE,
	WARPED_NYLIUM,
	WARPED_PLANKS,
	WARPED_PRESSURE_PLATE,
	WARPED_ROOTS,
	WARPED_SIGN("SIGN_POST"),
	WARPED_SLAB,
	WARPED_STAIRS,
	WARPED_STEM,
	WARPED_TRAPDOOR,
	WARPED_WALL_HANGING_SIGN,
	WARPED_WALL_SIGN("WALL_SIGN"),
	WARPED_WART_BLOCK,
	/**
	 * 仅用于方块。
	 * 在 1.13 之前，WATER 在扩散完成后会变为 STATIONARY_WATER。
	 * 1.13+ 之后使用
	 * <a href="https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/data/Levelled.html">Levelled</a> 水流系统。
	 */
	WATER("STATIONARY_WATER"),
	WATER_BUCKET,
	WATER_CAULDRON,
	WAXED_CHISELED_COPPER,
	WAXED_COPPER_BLOCK,
	WAXED_COPPER_BULB,
	WAXED_COPPER_DOOR,
	WAXED_COPPER_GRATE,
	WAXED_COPPER_TRAPDOOR,
	WAXED_CUT_COPPER,
	WAXED_CUT_COPPER_SLAB,
	WAXED_CUT_COPPER_STAIRS,
	WAXED_EXPOSED_CHISELED_COPPER,
	WAXED_EXPOSED_COPPER,
	WAXED_EXPOSED_COPPER_BULB,
	WAXED_EXPOSED_COPPER_DOOR,
	WAXED_EXPOSED_COPPER_GRATE,
	WAXED_EXPOSED_COPPER_TRAPDOOR,
	WAXED_EXPOSED_CUT_COPPER,
	WAXED_EXPOSED_CUT_COPPER_SLAB,
	WAXED_EXPOSED_CUT_COPPER_STAIRS,
	WAXED_OXIDIZED_CHISELED_COPPER,
	WAXED_OXIDIZED_COPPER,
	WAXED_OXIDIZED_COPPER_BULB,
	WAXED_OXIDIZED_COPPER_DOOR,
	WAXED_OXIDIZED_COPPER_GRATE,
	WAXED_OXIDIZED_COPPER_TRAPDOOR,
	WAXED_OXIDIZED_CUT_COPPER,
	WAXED_OXIDIZED_CUT_COPPER_SLAB,
	WAXED_OXIDIZED_CUT_COPPER_STAIRS,
	WAXED_WEATHERED_CHISELED_COPPER,
	WAXED_WEATHERED_COPPER,
	WAXED_WEATHERED_COPPER_BULB,
	WAXED_WEATHERED_COPPER_DOOR,
	WAXED_WEATHERED_COPPER_GRATE,
	WAXED_WEATHERED_COPPER_TRAPDOOR,
	WAXED_WEATHERED_CUT_COPPER,
	WAXED_WEATHERED_CUT_COPPER_SLAB,
	WAXED_WEATHERED_CUT_COPPER_STAIRS,
	WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE,
	WEATHERED_CHISELED_COPPER,
	WEATHERED_COPPER,
	WEATHERED_COPPER_BULB,
	WEATHERED_COPPER_DOOR,
	WEATHERED_COPPER_GRATE,
	WEATHERED_COPPER_TRAPDOOR,
	WEATHERED_CUT_COPPER,
	WEATHERED_CUT_COPPER_SLAB,
	WEATHERED_CUT_COPPER_STAIRS,
	PALE_OAK_PLANKS,
	PALE_OAK_SAPLING,
	PALE_OAK_LOG,
	STRIPPED_PALE_OAK_LOG,
	STRIPPED_PALE_OAK_WOOD,
	PALE_OAK_WOOD,
	PALE_OAK_LEAVES,
	PALE_MOSS_CARPET,
	PALE_HANGING_MOSS,
	PALE_MOSS_BLOCK,
	PALE_OAK_SLAB,
	CREAKING_HEART,
	PALE_OAK_FENCE,
	PALE_OAK_STAIRS,
	PALE_OAK_BUTTON,
	PALE_OAK_PRESSURE_PLATE,
	PALE_OAK_DOOR,
	PALE_OAK_TRAPDOOR,
	PALE_OAK_FENCE_GATE,
	PALE_OAK_BOAT,
	PALE_OAK_CHEST_BOAT,
	PALE_OAK_SIGN,
	PALE_OAK_HANGING_SIGN,
	WHITE_BUNDLE,
	ORANGE_BUNDLE,
	MAGENTA_BUNDLE,
	LIGHT_BLUE_BUNDLE,
	YELLOW_BUNDLE,
	LIME_BUNDLE,
	PINK_BUNDLE,
	GRAY_BUNDLE,
	LIGHT_GRAY_BUNDLE,
	CYAN_BUNDLE,
	PURPLE_BUNDLE,
	BLUE_BUNDLE,
	BROWN_BUNDLE,
	GREEN_BUNDLE,
	RED_BUNDLE,
	BLACK_BUNDLE,
	CREAKING_SPAWN_EGG,
	FIELD_MASONED_BANNER_PATTERN,
	BORDURE_INDENTED_BANNER_PATTERN,
	PALE_OAK_WALL_SIGN,
	PALE_OAK_WALL_HANGING_SIGN,
	POTTED_PALE_OAK_SAPLING,
	WEEPING_VINES,
	WEEPING_VINES_PLANT,
	WET_SPONGE(1, "SPONGE"),
	/**
	 * 小麦在 1.13 之前是已知材质
	 */
	WHEAT("CROPS"),
	WHEAT_SEEDS("SEEDS"),
	WHITE_BANNER(15, "STANDING_BANNER", "BANNER"),
	WHITE_BED("BED_BLOCK", "BED"),
	WHITE_CANDLE,
	WHITE_CANDLE_CAKE,
	WHITE_CARPET("CARPET"),
	WHITE_CONCRETE("CONCRETE"),
	WHITE_CONCRETE_POWDER("CONCRETE_POWDER"),
	WHITE_DYE(15, "INK_SACK", "BONE_MEAL"),
	WHITE_GLAZED_TERRACOTTA,
	WHITE_SHULKER_BOX,
	WHITE_STAINED_GLASS("STAINED_GLASS"),
	WHITE_STAINED_GLASS_PANE("THIN_GLASS", "STAINED_GLASS_PANE"),
	WHITE_TERRACOTTA("STAINED_CLAY"),
	WHITE_TULIP(6, "RED_ROSE"),
	WHITE_WALL_BANNER(15, "WALL_BANNER"),
	WHITE_WOOL("WOOL"),
	WILDFLOWERS,
	WILD_ARMOR_TRIM_SMITHING_TEMPLATE,
	WIND_CHARGE,
	WITCH_SPAWN_EGG(66, "MONSTER_EGG"),
	WITHER_ROSE,
	WITHER_SKELETON_SKULL(1, "SKULL", "SKULL_ITEM"),
	WITHER_SKELETON_SPAWN_EGG(5, "MONSTER_EGG"),
	WITHER_SKELETON_WALL_SKULL(1, "SKULL", "SKULL_ITEM"),
	WITHER_SPAWN_EGG,
	WOLF_ARMOR,
	WOLF_SPAWN_EGG(95, "MONSTER_EGG"),
	WOODEN_AXE("WOOD_AXE"),
	WOODEN_HOE("WOOD_HOE"),
	WOODEN_PICKAXE("WOOD_PICKAXE"),
	WOODEN_SHOVEL("WOOD_SPADE"),
	WOODEN_SWORD("WOOD_SWORD"),
	WRITABLE_BOOK("BOOK_AND_QUILL"),
	WRITTEN_BOOK,
	YELLOW_BANNER(11, "STANDING_BANNER", "BANNER"),
	YELLOW_BED(supports(12) ? 4 : 0, "BED_BLOCK", "BED"),
	YELLOW_CANDLE,
	YELLOW_CANDLE_CAKE,
	YELLOW_CARPET(4, "CARPET"),
	YELLOW_CONCRETE(4, "CONCRETE"),
	YELLOW_CONCRETE_POWDER(4, "CONCRETE_POWDER"),
	/**
	 * 1.13 重命名为 DANDELION_YELLOW
	 * 1.14 重命名为 YELLOW_DYE
	 */
	YELLOW_DYE(11, "INK_SACK", "DANDELION_YELLOW"),
	YELLOW_GLAZED_TERRACOTTA,
	YELLOW_SHULKER_BOX,
	YELLOW_STAINED_GLASS(4, "STAINED_GLASS"),
	YELLOW_STAINED_GLASS_PANE(4, "THIN_GLASS", "STAINED_GLASS_PANE"),
	YELLOW_TERRACOTTA(4, "STAINED_CLAY"),
	YELLOW_WALL_BANNER(11, "WALL_BANNER"),
	YELLOW_WOOL(4, "WOOL"),
	ZOGLIN_SPAWN_EGG,
	ZOMBIE_HEAD(2, "SKULL", "SKULL_ITEM"),
	ZOMBIE_HORSE_SPAWN_EGG(29, "MONSTER_EGG"),
	ZOMBIE_SPAWN_EGG(54, "MONSTER_EGG"),
	ZOMBIE_VILLAGER_SPAWN_EGG(27, "MONSTER_EGG"),
	ZOMBIE_WALL_HEAD(2, "SKULL", "SKULL_ITEM"),
	ZOMBIFIED_PIGLIN_SPAWN_EGG(57, "MONSTER_EGG", "ZOMBIE_PIGMAN_SPAWN_EGG"),

	// 1.21.4 new names:
	PEN_EYEBLOSSOM,
	CLOSED_EYEBLOSSOM,
	RESIN_CLUMP,
	RESIN_BLOCK,
	RESIN_BRICKS,
	RESIN_BRICK_STAIRS,
	RESIN_BRICK_SLAB,
	RESIN_BRICK_WALL,
	CHISELED_RESIN_BRICKS,
	RESIN_BRICK,
	POTTED_OPEN_EYEBLOSSOM,
	POTTED_CLOSED_EYEBLOSSOM,
	OPEN_EYEBLOSSOM,

	// 1.21.6 new names:
	BLACK_HARNESS,
	BLUE_HARNESS,
	BROWN_HARNESS,
	CYAN_HARNESS,
	GRAY_HARNESS,
	GREEN_HARNESS,
	HAPPY_GHAST_SPAWN_EGG,
	LIGHT_BLUE_HARNESS,
	LIGHT_GRAY_HARNESS,
	LIME_HARNESS,
	MAGENTA_HARNESS,
	MUSIC_DISC_TEARS,
	ORANGE_HARNESS,
	PINK_HARNESS,
	PURPLE_HARNESS,
	RED_HARNESS,
	WHITE_HARNESS,
	YELLOW_HARNESS,
	DRIED_GHAST,

	// 1.21.7 new names:
	MUSIC_DISC_LAVA_CHICKEN,

	// 1.21.9 new names:
	ACACIA_SHELF,
	BAMBOO_SHELF,
	BIRCH_SHELF,
	CHERRY_SHELF,
	CRIMSON_SHELF,
	DARK_OAK_SHELF,
	JUNGLE_SHELF,
	MANGROVE_SHELF,
	OAK_SHELF,
	PALE_OAK_SHELF,
	SPRUCE_SHELF,
	WARPED_SHELF,
	COPPER_TORCH,
	COPPER_BARS,
	EXPOSED_COPPER_BARS,
	WEATHERED_COPPER_BARS,
	OXIDIZED_COPPER_BARS,
	WAXED_COPPER_BARS,
	WAXED_EXPOSED_COPPER_BARS,
	WAXED_WEATHERED_COPPER_BARS,
	WAXED_OXIDIZED_COPPER_BARS,
	COPPER_CHAIN,
	EXPOSED_COPPER_CHAIN,
	WEATHERED_COPPER_CHAIN,
	OXIDIZED_COPPER_CHAIN,
	WAXED_COPPER_CHAIN,
	WAXED_EXPOSED_COPPER_CHAIN,
	WAXED_WEATHERED_COPPER_CHAIN,
	WAXED_OXIDIZED_COPPER_CHAIN,
	EXPOSED_LIGHTNING_ROD,
	WEATHERED_LIGHTNING_ROD,
	OXIDIZED_LIGHTNING_ROD,
	WAXED_LIGHTNING_ROD,
	WAXED_EXPOSED_LIGHTNING_ROD,
	WAXED_WEATHERED_LIGHTNING_ROD,
	WAXED_OXIDIZED_LIGHTNING_ROD,
	COPPER_SWORD,
	COPPER_SHOVEL,
	COPPER_PICKAXE,
	COPPER_AXE,
	COPPER_HOE,
	COPPER_HELMET,
	COPPER_CHESTPLATE,
	COPPER_LEGGINGS,
	COPPER_BOOTS,
	COPPER_GOLEM_SPAWN_EGG,
	COPPER_HORSE_ARMOR,
	COPPER_NUGGET,
	COPPER_LANTERN,
	EXPOSED_COPPER_LANTERN,
	WEATHERED_COPPER_LANTERN,
	OXIDIZED_COPPER_LANTERN,
	WAXED_COPPER_LANTERN,
	WAXED_EXPOSED_COPPER_LANTERN,
	WAXED_WEATHERED_COPPER_LANTERN,
	WAXED_OXIDIZED_COPPER_LANTERN,
	COPPER_CHEST,
	EXPOSED_COPPER_CHEST,
	WEATHERED_COPPER_CHEST,
	OXIDIZED_COPPER_CHEST,
	WAXED_COPPER_CHEST,
	WAXED_EXPOSED_COPPER_CHEST,
	WAXED_WEATHERED_COPPER_CHEST,
	WAXED_OXIDIZED_COPPER_CHEST,
	COPPER_GOLEM_STATUE,
	EXPOSED_COPPER_GOLEM_STATUE,
	WEATHERED_COPPER_GOLEM_STATUE,
	OXIDIZED_COPPER_GOLEM_STATUE,
	WAXED_COPPER_GOLEM_STATUE,
	WAXED_EXPOSED_COPPER_GOLEM_STATUE,
	WAXED_WEATHERED_COPPER_GOLEM_STATUE,
	WAXED_OXIDIZED_COPPER_GOLEM_STATUE,
	COPPER_WALL_TORCH,

	// Up to Minecraft 1.21.11
	CAMEL_HUSK_SPAWN_EGG,
	COPPER_NAUTILUS_ARMOR,
	COPPER_SPEAR,
	DIAMOND_NAUTILUS_ARMOR,
	DIAMOND_SPEAR,
	GOLDEN_NAUTILUS_ARMOR,
	GOLDEN_SPEAR,
	IRON_NAUTILUS_ARMOR,
	IRON_SPEAR,
	NAUTILUS_SPAWN_EGG,
	NETHERITE_HORSE_ARMOR,
	NETHERITE_NAUTILUS_ARMOR,
	NETHERITE_SPEAR,
	PARCHED_SPAWN_EGG,
	STONE_SPEAR,
	WOODEN_SPEAR,
	ZOMBIE_NAUTILUS_SPAWN_EGG;

	/**
	 * {@link CompMaterial#values()} 的缓存数组，避免每次调用该方法时
	 * 都分配内存。
	 *
	 * @since 2.0.0
	 */
	private static final CompMaterial[] VALUES = values();

	/**
	 * 我们不想使用 Enums#getIfPresent(Class, String)，以省去一些检查。
	 *
	 * @since 5.1.0
	 */
	private static final Map<String, CompMaterial> NAMES = new HashMap<>();

	/**
	 * 扁平化更新之前的最大数据值，属于 {@link #VILLAGER_SPAWN_EGG}<br>
	 * https://minecraftitemids.com/types/spawn-egg
	 *
	 * @see #matchWithData(String)
	 * @since 8.0.0
	 */
	private static final byte MAX_DATA_VALUE = 120;

	/**
	 * 用于告诉系统传入对象（名称或材质）的数据值
	 * 未提供或无效。
	 *
	 * @since 8.0.0
	 */
	private static final byte UNKNOWN_DATA_VALUE = -1;

	/**
	 * 扁平化更新之前的最大材质 ID，属于 {@link #MUSIC_DISC_WAIT}
	 *
	 * @since 8.1.0
	 */
	private static final short MAX_ID = 2267;

	/**
	 * <b>CompMaterial 悖论（重复检查）</b>
	 * <p>
	 * 1.13 与 1.12 中会与旧名称冲突的重复材质名称集合。
	 * 值为新的材质名称。此映射还包含非法元素，更多信息请查看静态初始化块。
	 * <p>
	 * 在扁平化更新 {@link Data#ISFLAT} 之后的版本中，重复项毫无用处
	 * 此集合仅用于匹配材质，解析请参见 {@link #isDuplicated()}
	 *
	 * @since 3.0.0
	 */
	private static final Set<String> DUPLICATED;

	static {
		for (final CompMaterial material : VALUES)
			NAMES.put(material.name(), material);

		if (Data.ISFLAT)
			// It's not needed at all if it's the newer version. We can save some memory.
			DUPLICATED = null;
		else {
			// MELON_SLICE, CARROTS, POTATOES, BEETROOTS, GRASS_BLOCK, BRICKS, NETHER_BRICKS, BROWN_MUSHROOM
			// Using the constructor to add elements will decide to allocate more size which we don't need.
			DUPLICATED = new HashSet<>(4);
			DUPLICATED.add("GRASS");
			DUPLICATED.add(MELON.name());
			DUPLICATED.add(BRICK.name());
			DUPLICATED.add(NETHER_BRICK.name());
		}
	}

	/**
	 * 此材质在<a href="https://minecraft.wiki/w/Java_Edition_data_values/Pre-flattening">扁平化之前</a>的数据值。
	 *
	 * 可通过 {@link ItemStack#getData()} 再调用 {@code MaterialData#getData()} 获取，
	 * 若不可损坏，也可通过 {@link ItemStack#getDurability()} 获取。
	 */
	@Getter
	private final byte data;

	/**
	 * 此材质被添加时的版本；若未记录版本则为 0。
	 *
	 * @see #getMaterialVersion()
	 * @since 7.0.0
	 */
	private final int version;

	/**
	 * 旧版本中使用过的材质名称列表。
	 *
	 * @see #getClosestLegacyAlternatives()
	 */
	private final String[] legacy;

	/**
	 * 缓存的 Bukkit 解析后的材质。
	 *
	 * @see #getMaterial()
	 * @since 9.0.0
	 */
	@Getter
	private final Material material;

	CompMaterial(final int data, final int version, final String... legacy) {
		this.data = (byte) data;
		this.version = version;
		this.legacy = legacy;

		Material mat = null;

		if (!Data.ISFLAT && this.isDuplicated() || (mat = Material.getMaterial(this.name())) == null)
			for (int i = legacy.length - 1; i >= 0; i--) {
				mat = Material.getMaterial(legacy[i]);

				if (mat != null)
					break;
			}

		this.material = CommonCore.getOrDefault(mat, Material.STONE);
	}

	CompMaterial(final int data, final String... legacy) {
		this(data, 0, legacy);
	}

	CompMaterial(final int version) {
		this(0, version);
	}

	CompMaterial() {
		this(0, 0);
	}

	CompMaterial(final String... legacy) {
		this(0, 0, legacy);
	}

	/**
	 * 便捷方法，将 1 个此材质放入玩家背包
	 *
	 * @param player
	 */
	public final void give(final Player player) {
		this.give(player, 1);
	}

	/**
	 * 便捷方法，将此材质放入玩家背包
	 *
	 * @param player
	 * @param amount
	 */
	public final void give(final Player player, final int amount) {
		player.getInventory().addItem(this.toItem(amount));
	}

	/**
	 * 根据此 CompMaterial 解析出物品。
	 * 在旧版本上会使用数据值。
	 *
	 * @return 材质相同（旧版本中还包括数据值）的 ItemStack。
	 * @see #setType(ItemStack)
	 */

	public ItemStack toItem() {
		return this.toItem(1);
	}

	/**
	 * 根据此 CompMaterial 解析出物品。
	 * 在旧版本上会使用数据值。
	 *
	 * @return 材质相同（旧版本中还包括数据值）的 ItemStack。
	 * @see #setType(ItemStack)
	 *
	 * @param amount
	 */

	public ItemStack toItem(final int amount) {
		final Material material = this.getMaterial();

		if (material == null)
			return null;

		return Data.ISFLAT ? new ItemStack(material, amount) : new ItemStack(material, amount, this.data);
	}

	/**
	 * 若 {@link #getMaterial()} 与给定 Material 匹配则返回 true。
	 * <p>
	 * 不跨版本兼容。如需跨版本兼容，请使用 {@link #is(ItemStack)}
	 *
	 * @param mat
	 * @return
	 */
	public final boolean is(final Material mat) {
		return this.material == mat;
	}

	/**
	 * 判断给定 {@link ItemStack} 在材质上是否相同。无论运行在
	 * Minecraft 1.13+ 还是更旧版本，都会考虑数据值。
	 *
	 * @param comp 物品堆
	 * @return -见上文-
	 */
	public final boolean is(final ItemStack comp) {
		if (MinecraftVersion.atLeast(V.v1_13))
			return comp.getType() == this.material;

		return this.is(comp.getType(), comp.getData().getData());
	}

	/**
	 * 判断给定方块是否等于此材质
	 *
	 * @param block
	 * @return
	 */
	public final boolean is(final Block block) {
		if (MinecraftVersion.atLeast(V.v1_13))
			return block.getType() == this.material;

		return block != null && this.is(block.getType(), block.getData());
	}

	/**
	 * 判断给定类型/数据值是否等于此材质
	 *
	 * @param type
	 * @param data
	 * @return
	 */
	public final boolean is(final Material type, final int data) {
		if (MinecraftVersion.atLeast(V.v1_13))
			return type == this.material;

		if (type == this.getMaterial() && data == this.data)
			return true;

		final CompMaterial compMat = fromMaterial(type);

		return isDamageable(compMat) && this.getMaterial() == type;
	}

	/**
	 * 对可损坏的材质返回 true。
	 *
	 * @return
	 */
	public final boolean isDamageable() {
		return isDamageable(this);
	}

	/**
	 * 若此类等于给定方块则返回 true，会比较数据值和 {@link Material} 类型
	 *
	 * @param block
	 * @return
	 */
	public final boolean equals(final Block block) {
		return block.getData() == this.getData() && block.getType() == this.material;
	}

	/**
	 * 若给定材质可损坏则返回 true。
	 *
	 * @param type
	 * @return
	 */
	public static boolean isDamageable(final CompMaterial type) {
		ValidCore.checkNotNull(type);

		try {
			if (MinecraftVersion.atLeast(V.v1_13))
				return type.toItem().getItemMeta() instanceof org.bukkit.inventory.meta.Damageable;
		} catch (final Throwable t) {
			// MC unsupported
		}

		switch (type.toString()) {
			case "HELMET":
			case "CHESTPLATE":
			case "LEGGINGS":
			case "BOOTS":
			case "SWORD":
			case "AXE":
			case "PICKAXE":
			case "SHOVEL":
			case "HOE":
			case "ELYTRA":
			case "TURTLE_HELMET":
			case "TRIDENT":
			case "HORSE_ARMOR":
			case "SHEARS":
				return true;
			default:
				return false;
		}
	}

	/**
	 * 若给定方块是空气则返回 true
	 *
	 * @param block
	 * @return
	 */
	public static boolean isAir(final Block block) {
		return block == null || isAir(block.getType());
	}

	/**
	 * 返回给定物品堆是否为空气
	 *
	 * @param item
	 * @return
	 */
	public static boolean isAir(final ItemStack item) {
		return item == null || isAir(item.getType());
	}

	/**
	 * 返回给定材质是否为空气
	 *
	 * @param material
	 * @return
	 */
	public static boolean isAir(final Material material) {
		return material == null || isAir(ReflectionUtil.getEnumName(material));
	}

	/**
	 * 返回给定材质是否为空气
	 * @param materialName
	 * @return
	 */
	public static boolean isAir(final String materialName) {
		return materialName == null || "AIR".equals(materialName) || "CAVE_AIR".equals(materialName) || "VOID_AIR".equals(materialName) || "LEGACY_AIR".equals(materialName);
	}

	/**
	 * 返回给定材质是否为空气
	 * @param material
	 * @return
	 */
	public static boolean isAir(final CompMaterial material) {
		return material == null || material == AIR || material == CAVE_AIR || material == VOID_AIR;
	}

	/**
	 * 若给定材质是床方块（任意颜色）或床物品则返回 true。
	 *
	 * @param block
	 * @return
	 */
	public static boolean isBed(final Block block) {
		return isBed(block.getType());
	}

	/**
	 * 若给定材质是床方块（任意颜色）或床物品则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isBed(final Material mat) {
		return nameEquals(mat, "BED", "BED_BLOCK") || nameContains(mat, "_BED");
	}

	/**
	 * 若给定材质是马铠（旧称 barding）则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isHorseArmor(final Material mat) {
		return nameEquals(mat, "BARDING", "HORSE_ARMOR");
	}

	/**
	 * 若给定材质是地毯（任意变种）则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isCarpet(final Material mat) {
		return nameContains(mat, "CARPET");
	}

	/**
	 * 若给定材质是树叶（任意变种）则返回 true
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isLeaves(final Material mat) {
		return mat.toString().endsWith("_LEAVES") || nameEquals(mat, "LEAVES", "LEAVES_2");
	}

	/**
	 * 若给定材质是硬化粘土（任意变种，后来
	 * 更名为陶瓦）则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isHardClay(final Material mat) {
		return nameContains(mat, "STAINED_CLAY", "HARD_CLAY", "TERRACOTTA");
	}

	/**
	 * 若给定材质是马用拴绳则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isLeash(final Material mat) {
		return nameEquals(mat, "LEASH", "LEAD");
	}

	/**
	 * 若给定材质是金质或铁质压力板则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isHeavyPressurePlate(final Material mat) {
		return nameContains(mat, "IRON_PLATE", "GOLD_PLATE", "WEIGHTED_PRESSURE_PLATE");
	}

	/**
	 * 对所有种类的木质压力板返回 true
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isWoodPressurePlate(final Material mat) {
		return nameEquals(mat, "WOOD_PLATE", "ACACIA_PRESSURE_PLATE", "BIRCH_PRESSURE_PLATE", "DARK_OAK_PRESSURE_PLATE",
				"JUNGLE_PRESSURE_PLATE", "OAK_PRESSURE_PLATE", "SPRUCE_PRESSURE_PLATE");
	}

	/**
	 * 若给定材质是烟花则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isFirework(final Material mat) {
		return nameContains(mat, "FIREWORK");
	}

	/**
	 * 若给定材质是原木（任意变种）则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isLog(final Material mat) {
		return nameEquals(mat, "LOG", "LOG_2") || mat.toString().endsWith("_LOG");
	}

	/**
	 * 若给定材质是船（没错）（任意变种）则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isBoat(final Material mat) {
		return nameContains(mat, "BOAT");
	}

	/**
	 * 若给定材质是木质按钮（任意变种）则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isWoodButton(final Material mat) {
		final String n = mat.toString();

		return n.endsWith("_BUTTON") && !n.equals("STONE_BUTTON");
	}

	/**
	 * 若给定材质是红石灯（任意状态）则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isRedstoneLamp(final Material mat) {
		return nameContains(mat, "REDSTONE_LAMP");
	}

	/**
	 * 若给定材质是刷怪蛋则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isMonsterEgg(final Material mat) {
		return nameContains(mat, "MONSTER_EGG", "_SPAWN_EGG");
	}

	/**
	 * 若给定材质是树苗（非盆栽）则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isSapling(final Material mat) {
		return nameContains(mat, "SAPLING") && !mat.toString().startsWith("POTTED");
	}

	/**
	 * 若给定材质是墙上告示牌（任意变种）则返回 true。
	 *
	 * @param mat 材质
	 * @return
	 */
	public static boolean isWallSign(final Material mat) {
		return nameContains(mat, "WALL_SIGN");
	}

	/**
	 * 若给定材质是枯死的灌木或草则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isLongGrass(final Material mat) {
		return nameEquals(mat, "LONG_GRASS", "TALL_GRASS", "FERN", "DEAD_BUSH") && !mat.toString().startsWith("POTTED");
	}

	/**
	 * 若给定材质放置后通常有 2 格高则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isDoublePlant(final Material mat) {
		return nameEquals(mat, "DOUBLE_PLANT", "SUNFLOWER", "LILAC", "TALL_GRASS", "LARGE_FERN", "ROSE_BUSH", "PEONY", "TALL_SEAGRASS");
	}

	/**
	 * 若给定材质是头颅则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isSkull(final CompMaterial mat) {
		return isSkull(mat.getMaterial());
	}

	/**
	 * 若给定材质是头颅则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isSkull(final Material mat) {
		final String name = mat.toString();

		return (name.endsWith("_HEAD") || name.endsWith("_SKULL")) && !name.contains("WALL");
	}

	/**
	 * 若给定材质是活板门（任意变种）则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isTrapDoor(final Material mat) {
		final String name = mat.toString();

		return name.contains("TRAP_DOOR") || name.contains("TRAPDOOR");
	}

	/**
	 * 若给定材质是头盔或可充当头盔则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isHelmet(final Material mat) {
		final String name = mat.toString();
		return name.endsWith("_HELMET") ||
				isSkull(mat) ||
				nameEquals(mat, MinecraftVersion.atLeast(V.v1_13) ? "CARVED_PUMPKIN" : "PUMPKIN");

	}

	/**
	 * 若给定材质是胸甲或可充当胸甲则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isChestplate(final Material mat) {
		final String name = mat.toString();
		return name.endsWith("_CHESTPLATE") || nameEquals(mat, "ELYTRA");
	}

	/**
	 * 若给定材质是护腿或可充当护腿则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isLeggings(final Material mat) {
		return mat.toString().endsWith("_LEGGINGS");
	}

	/**
	 * 若给定材质是靴子或可充当靴子则返回 true。
	 *
	 * @param mat
	 * @return
	 */
	public static boolean isBoots(final Material mat) {
		return mat.toString().endsWith("_BOOTS");
	}

	// Utility method for evaluating matches.
	private static boolean nameContains(final Material mat, final String... names) {
		final String matName = mat.toString();

		for (final String name : names)
			if (matName.contains(name))
				return true;

		return false;
	}

	// Utility method for evaluating matches.
	private static boolean nameEquals(final Material mat, final String... names) {
		final String matName = mat.toString();

		for (final String name : names)
			if (matName.equals(name))
				return true;

		return false;
	}

	/**
	 * 根据给定数据类型和数量创建羊毛。
	 *
	 * @deprecated 请改用 {@link #makeWoolItem(CompColor, int)}。
	 *
	 * @param color
	 * @param amount
	 * @return
	 */
	@Deprecated
	public static ItemStack makeWool(final byte color, final int amount) {
		return makeWoolItem(color, amount);
	}

	/**
	 * 根据染料创建一定数量的羊毛。
	 *
	 * @deprecated 请改用 {@link #makeWoolItem(CompColor, int)}。
	 *
	 * @param color
	 * @param amount
	 * @return
	 */
	@Deprecated
	public static ItemStack makeWool(final CompColor color, final int amount) {
		return makeWoolItem(color, amount);
	}

	/**
	 * 根据给定数据类型和数量创建羊毛。
	 *
	 * @param color
	 * @param amount
	 * @return
	 */
	public static ItemStack makeWoolItem(final byte color, final int amount) {
		return makeWoolItem(CompColor.fromWoolData(color), amount);
	}

	/**
	 * 根据染料创建一定数量的羊毛。
	 *
	 * @param color
	 * @param amount
	 * @return
	 */
	public static ItemStack makeWoolItem(final CompColor color, final int amount) {
		if (MinecraftVersion.atLeast(V.v1_13))
			return new ItemStack(ReflectionUtil.lookupEnum(Material.class, color.getDye() + "_WOOL"), amount);

		else
			return new ItemStack(ReflectionUtil.lookupEnum(Material.class, "WOOL"), amount, color.getDye().getWoolData());
	}

	/*
	 * Gets the CompMaterial with this name similar to {@link #valueOf(String)}
	 * without throwing an exception.
	 *
	 * @param name the name of the material.
	 *
	 * @return an optional that can be empty.
	 * @since 5.1.0
	 */
	private static CompMaterial getIfPresent(final String name) {
		return NAMES.get(name);
	}

	/*
	 * When using 1.13+, this helps to find the old material name
	 * with its data value using a cached search for optimization.
	 *
	 * @see #matchDefinedCompMaterial(String, byte)
	 * @since 1.0.0
	 */
	private static CompMaterial requestOldMaterial(final String name, final int data) {

		for (final CompMaterial material : VALUES)
			// Not using material.name().equals(name) check is intended.
			if ((data == UNKNOWN_DATA_VALUE || data == material.data) && material.anyMatchLegacy(name))
				return material;

		return null;
	}

	/**
	 * 将给定材质名称解析为 CompMaterial，若字符串中附带数据值
	 * 则一并解析。更多信息请参见 matchWithData。
	 *
	 * @param key
	 * @return
	 */
	public static CompMaterial fromString(String key) {

		// try to resolve common pitfalls and emulate the material enum writing style
		key = key.replace(" ", "_").toUpperCase();

		// Translate generic monster egg to sheep instead of the white unattributed egg on MC 1.13+
		if (MinecraftVersion.atLeast(V.v1_13) && key.equals("MONSTER_EGG"))
			key = "SHEEP_SPAWN_EGG";

		final CompMaterial oldMatch = matchWithData(key);

		return oldMatch != null ? oldMatch : fromLegacy(format(key), UNKNOWN_DATA_VALUE);
	}

	/*
	 * Parses material name and data value from the specified string.
	 * The separator for the material name and its data value is {@code :}
	 * Spaces are allowed. Mostly used when getting materials from config for old school minecrafters.
	 * <p>
	 * <b>Examples</b>
	 * <p><pre>
	 *     {@code INK_SACK:1 -> RED_DYE}
	 *     {@code WOOL: 14  -> RED_WOOL}
	 * </pre>
	 *
	 * @param name the material string that consists of the material name, data and separator character.
	 *
	 * @return the parsed CompMaterial.
	 * @see #matchCompMaterial(String)
	 * @since 3.0.0
	 */
	private static CompMaterial matchWithData(final String name) {
		final int index = name.indexOf(':');

		if (index != -1) {
			final String mat = format(name.substring(0, index));

			try {
				// We don't use Byte.parseByte because we have our own range check.
				final byte data = (byte) Integer.parseInt(name.substring(index + 1).replace(" ", ""));
				return data >= 0 && data < MAX_DATA_VALUE ? fromLegacy(mat, data) : fromLegacy(mat, UNKNOWN_DATA_VALUE);

			} catch (final NumberFormatException ignored) {
				return fromLegacy(mat, UNKNOWN_DATA_VALUE);
			}
		}

		return null;
	}

	/**
	 * 根据给定方块返回 {@link CompMaterial}，同时比较数据值
	 *
	 * @param block
	 * @return
	 */
	public static CompMaterial fromBlock(final Block block) {
		return MinecraftVersion.atLeast(V.v1_13) ? fromMaterial(block.getType()) : fromLegacy(block.getType().toString(), block.getData());
	}

	/**
	 * 使用物品的材质和数据值（耐久度，仅当不是可损坏物品时，见 {@link ItemStack#getDurability()}）
	 * 将给定物品解析为 CompMaterial。
	 *
	 * @param item 要匹配的 ItemStack。
	 *
	 * @return 若有匹配则返回 CompMaterial。
	 * @throws IllegalArgumentException 可能作为意外异常抛出。
	 * @see #fromMaterial(Material)
	 * @since 2.0.0
	 */
	public static CompMaterial fromItem(@NonNull final ItemStack item) {
		final String material = ReflectionUtil.getEnumName(item.getType());
		final byte data = (byte) (Data.ISFLAT || item.getType().getMaxDurability() > 0 ? 0 : item.getDurability());

		CompMaterial compmaterial = fromLegacy(material, data);

		// Exception for legacy eggs for non existing entities
		if (material.equals("MONSTER_EGG") && compmaterial == null)
			return CompMaterial.SHEEP_SPAWN_EGG;

		if (compmaterial == null)
			compmaterial = fromString(material);

		ValidCore.checkNotNull(compmaterial, "Could not convert item to CompMaterial. Material: " + material + ", data: " + data);

		return compmaterial;
	}

	/**
	 * 将给定材质解析为 CompMaterial。
	 *
	 * @param material
	 * @return
	 */
	public static CompMaterial fromMaterial(@NonNull final Material material) {

		try {
			return CompMaterial.valueOf(material.toString());

		} catch (final Throwable t) {
			final CompMaterial compmaterial = fromLegacy(ReflectionUtil.getEnumName(material), UNKNOWN_DATA_VALUE);
			ValidCore.checkNotNull(compmaterial, "Unsupported material with no data value: " + material);

			return compmaterial;

		}
	}

	/**
	 * 参见 {@link #fromString(String)}，不同之处在于
	 * 若字符串无法解析，此方法会抛出错误
	 *
	 * @param key
	 * @return
	 */
	public static CompMaterial fromStringStrict(final String key) {
		final CompMaterial material = fromString(key);

		ValidCore.checkNotNull(material, "Invalid material '" + key + "'! For valid names, see: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html (Note that names change across MC versions!)");
		return material;
	}

	/**
	 * 将给定材质名称和数据值解析为 CompMaterial 的主方法。
	 * 传入此方法的所有值都不会为 null 或空，并且格式正确。
	 *
	 * @param name
	 * @param data
	 * @return
	 */
	public static CompMaterial fromLegacy(String name, final int data) {

		// try to resolve common pitfalls and emulate the material enum writing style
		name = name.replace(" ", "_").toUpperCase();

		// CompMaterial does not support legacy names
		name = name.replace("LEGACY_", "");

		Boolean duplicated = null;
		final boolean isAMap = name.equalsIgnoreCase("MAP");

		// Do basic number and boolean checks before accessing more complex enum stuff.
		if (Data.ISFLAT || !isAMap && data <= 0 && !(duplicated = isDuplicated(name))) {
			final CompMaterial compmaterial = getIfPresent(name);

			if (compmaterial != null)
				return compmaterial;
		}
		// Usually flat versions wouldn't pass this point, but some special materials do.

		final CompMaterial oldCompmaterial = requestOldMaterial(name, data);

		if (oldCompmaterial == null)
			// Special case. Refer to FILLED_MAP for more info.
			return data >= 0 && isAMap ? FILLED_MAP : null;

		if (!Data.ISFLAT && oldCompmaterial.isPlural() && (duplicated == null ? isDuplicated(name) : duplicated))
			return getIfPresent(name);

		return oldCompmaterial;
	}

	/*
	 * <b>CompMaterial Paradox (Duplication Check)</b>
	 * Checks if the material has any duplicates.
	 * <p>
	 * <b>Example:</b>
	 * <p>{@code MELON, CARROT, POTATO, BEETROOT -> true}
	 *
	 * @param name the name of the material to check.
	 *
	 * @return true if there's a duplicated material for this material, otherwise false.
	 * @since 2.0.0
	 */
	private static boolean isDuplicated(final String name) {
		// Don't use matchCompMaterial() since this method is being called from matchCompMaterial() itself and will cause a StackOverflowError.
		return DUPLICATED.contains(name);
	}

	/**
	 * 根据材质的 ID（魔法值）和数据值获取 CompMaterial。<br>
	 * 出于性能考虑，应避免使用此方法。
	 *
	 * @param id   材质的 ID（魔法值）。
	 * @param data 材质的数据值。
	 *
	 * @return ID 和数据值相同的已解析 CompMaterial。
	 * @see #fromItem(ItemStack)
	 * @since 2.0.0
	 */
	public static CompMaterial fromId(final int id, final byte data) {
		if (id < 0 || id > MAX_ID || data < 0)
			return null;

		for (final CompMaterial materials : VALUES)
			if (materials.data == data && materials.getId() == id)
				return materials;

		return null;
	}

	/**
	 * 尝试将字符串构造成枚举名称的形式。
	 * 移除所有空格和额外的非英文字符，还会移除一些配置/游戏内使用的字符串。
	 * 虽然此方法难以维护，但效率极高。无论材质名称是否已格式化，它都比
	 * 普通的正则 + 字符串方法快大约 5 倍以上。
	 *
	 * @param name 要修改的材质名称。
	 *
	 * @return 枚举名称。
	 * @since 2.0.0
	 */
	protected static String format(final String name) {
		final int len = name.length();
		final char[] chs = new char[len];
		int count = 0;
		boolean appendUnderline = false;

		for (int i = 0; i < len; i++) {
			final char ch = name.charAt(i);

			if (!appendUnderline && count != 0 && (ch == '-' || ch == ' ' || ch == '_') && chs[count] != '_')
				appendUnderline = true;
			else {
				boolean number = false;
				// Old materials have numbers in them.
				if (ch >= 'A' && ch <= 'Z' || ch >= 'a' && ch <= 'z' || (number = ch >= '0' && ch <= '9')) {
					if (appendUnderline) {
						chs[count++] = '_';
						appendUnderline = false;
					}

					if (number)
						chs[count++] = ch;
					else
						chs[count++] = (char) (ch & 0x5f);
				}
			}
		}

		return new String(chs, 0, count);
	}

	/*
	 * Checks if the specified version is the same version or higher than the current server version.
	 *
	 * @param version the major version to be checked. "1." is ignored. E.g. 1.12 = 12 | 1.9 = 9
	 *
	 * @return true of the version is equal or higher than the current version.
	 * @since 2.0.0
	 */
	private static boolean supports(final int version) {
		return Data.VERSION >= version;
	}

	/*
	 * Gets the exact major version (..., 1.9, 1.10, ..., 1.14)
	 * In most cases, you shouldn't be using this method.
	 *
	 * @param version Supports {@link Bukkit#getVersion()}, {@link Bukkit#getBukkitVersion()} and normal formats such as "1.14"
	 *
	 * @return the exact major version.
	 * @see #supports(int)
	 * @see #getVersion()
	 * @see #getMaterialVersion()
	 * @since 2.0.0
	 */

	private static String getMajorVersion(@NonNull String version) {

		// getVersion()
		int index = version.lastIndexOf("MC:");
		if (index != -1)
			version = version.substring(index + 4, version.length() - 1);
		else if (version.endsWith("SNAPSHOT")) {
			// getBukkitVersion()
			index = version.indexOf('-');
			version = version.substring(0, index);
		}

		// 1.13.2, 1.14.4, etc...
		final int lastDot = version.lastIndexOf('.');
		if (version.indexOf('.') != lastDot)
			version = version.substring(0, lastDot);

		return version;
	}

	/*
	 * CompMaterial Paradox (Duplication Check)
	 * I've concluded that this is just an infinite loop that keeps
	 * going around the Singular Form and the Plural Form materials. A waste of brain cells and a waste of time.
	 * This solution works just fine anyway.
	 * <p>
	 * A solution for CompMaterial Paradox.
	 * Manually parses the duplicated materials to find the exact material based on the server version.
	 * If the name ends with "S" -> Plural Form Material.
	 * Plural methods are only plural if they're also {@link #DUPLICATED}
	 * <p>
	 * The only special exceptions are {@link #BRICKS} and {@link #NETHER_BRICKS}
	 *
	 * @return true if this material is a plural form material, otherwise false.
	 * @since 8.0.0
	 */
	private boolean isPlural() {
		return this == CARROTS || this == POTATOES;
	}

	/**
	 * 检查给定的材质名称列表是否与给定的基础材质匹配。
	 * 主要用于配置文件。
	 * <p>
	 * 支持 {@link String#contains} {@code CONTAINS:NAME} 格式。
	 * <p>
	 * <b>示例：</b>
	 * <blockquote><pre>
	 *     CompMaterial material = {@link #fromItem(ItemStack)};
	 *     if (material.isOneOf(plugin.getConfig().getStringList("disabled-items")) return;
	 * </pre></blockquote>
	 * <br>
	 * <b>{@code CONTAINS} 示例：</b>
	 * <pre>
	 *     {@code "CONTAINS:CHEST" -> CHEST, ENDERCHEST, TRAPPED_CHEST -> true}
	 *     {@code "cOnTaINS:dYe" -> GREEN_DYE, YELLOW_DYE, BLUE_DYE, INK_SACK -> true}
	 * </pre>
	 * <p>
	 * 为 {@code CONTAINS} 设置标签是出于性能考虑。
	 *
	 * <p>
	 *
	 * @param materials 要与基础材质进行检查的材质名称。
	 *
	 * @return 若给定材质名称之一与基础材质相似则为 true。
	 * @since 3.1.1
	 */
	public boolean isOneOf(final Collection<String> materials) {
		if (materials == null || materials.isEmpty())
			return false;
		final String name = this.name();

		for (String comp : materials) {
			final String checker = comp.toUpperCase(Locale.ENGLISH);
			if (checker.startsWith("CONTAINS:")) {
				comp = format(checker.substring(9));

				if (name.contains(comp))
					return true;

				continue;
			}

			// Direct Object Equals
			final CompMaterial xMat = fromString(comp);

			if (xMat != null && xMat == this)
				return true;
		}
		return false;
	}

	/**
	 * 设置物品的 {@link Material}（旧版本中还包括数据值）。
	 * 可损坏材质的耐久度不会被修改。
	 * <p>
	 * 创建新的 ItemStack 时请改用 {@link #toItem()}。
	 *
	 * @param item 要修改其类型的物品。
	 * @return
	 *
	 * @see #toItem()
	 * @since 3.0.0
	 */
	public ItemStack setType(final ItemStack item) {
		Objects.requireNonNull(item, "Cannot set material for null ItemStack");
		final Material material = this.getMaterial();
		Objects.requireNonNull(material, () -> "Unsupported material: " + this.name());

		item.setType(material);
		if (!Data.ISFLAT && material.getMaxDurability() <= 0)
			item.setDurability(this.data);

		return item;
	}

	/*
	 * Checks if the given material name matches any of this CompMaterial's legacy material names.
	 * All the values passed to this method will not be null or empty and are formatted correctly.
	 *
	 * @param name the material name to check.
	 *
	 * @return true if it's one of the legacy names, otherwise false.
	 * @since 2.0.0
	 */
	private boolean anyMatchLegacy(final String name) {
		for (int i = this.legacy.length - 1; i >= 0; i--)
			if (name.equals(this.legacy[i]))
				return true;
		return false;
	}

	/**
	 * 获取材质的 ID（魔法值）。
	 * https://www.minecraftinfo.com/idlist.htm
	 *
	 * @return 材质的 ID；若不是旧版材质或服务器不支持该材质则为 <b>-1</b>。
	 * @see #fromId(int, byte)
	 * @since 2.2.0
	 */
	public int getId() {
		if (this.data != 0 || this.version >= 13)
			return -1;

		final Material material = this.getMaterial();

		if (material == null)
			return -1;

		try {
			if (Data.ISFLAT && !material.isLegacy())
				return -1;
		} catch (final Throwable t) {
		}

		return material.getId();
	}

	/**
	 * @param item
	 * @return
	 * @see ItemUtil#isSimilar(ItemStack, ItemStack)
	 */
	public boolean isSimilar(final ItemStack item) {
		return ItemUtil.isSimilar(this.toItem(), item);
	}

	/*
	 * This method is needed due to Java enum initialization limitations.
	 * It's really inefficient yes, but it's only used for initialization.
	 * <p>
	 * Yes there are many other ways like comparing the hardcoded ordinal or using a boolean in the enum constructor,
	 * but it's not really a big deal.
	 * <p>
	 * This method should not be called if the version is after the flattening update {@link Data#ISFLAT}
	 * and is only used for parsing materials, not matching, for matching check {@link #DUPLICATED}
	 */
	private boolean isDuplicated() {
		switch (this.name()) {
			case "MELON":
			case "CARROT":
			case "POTATO":
			case "GRASS":
			case "BRICK":
			case "NETHER_BRICK":

				// Illegal Elements
				// Since both 1.12 and 1.13 have <type>_DOOR CompMaterial will use it
				// for 1.12 to parse the material, but it needs <type>_DOOR_ITEM.
				// We'll trick CompMaterial into thinking this needs to be parsed
				// using the old methods.
				// Some of these materials have their enum name added to the legacy list as well.
			case "DARK_OAK_DOOR":
			case "ACACIA_DOOR":
			case "BIRCH_DOOR":
			case "JUNGLE_DOOR":
			case "SPRUCE_DOOR":
			case "MAP":
			case "CAULDRON":
			case "BREWING_STAND":
			case "FLOWER_POT":
				return true;
			default:
				return false;
		}
	}

	/**
	 * 用于需要在枚举初始化期间访问的数据。
	 *
	 * @since 9.0.0
	 */
	private static final class Data {
		private static final int VERSION;

		static {
			final String ver = getMajorVersion(Bukkit.getVersion());
			final String[] parts = ver.split("\\.");
			final int major = Integer.parseInt(parts[0]);
			final int minor = Integer.parseInt(parts[1]);

			VERSION = major == 1 ? minor : major * 100 + minor;
		}

		private static final boolean ISFLAT = supports(13);
	}
}