// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/lex/jsonstrict.lex

package top.brmc.devlib.jsonsimple;

// See https://github.com/jflex-de/jflex/issues/222
class Yylex {

	/** 此字符表示文件结束。 */
	public static final int YYEOF = -1;

	/** 预读缓冲区的初始大小。 */
	private static final int ZZ_BUFFERSIZE = 16384;

	// Lexical states.
	public static final int YYINITIAL = 0;
	public static final int STRING_BEGIN = 2;

	/**
	 * ZZ_LEXSTATE[l] 是词法状态 l 在 DFA 中对应的状态
	 * ZZ_LEXSTATE[l+1] 是词法状态 l 在行首时
	 *                  在 DFA 中对应的状态
	 * l 的形式为 l = 2*k，k 为非负整数
	 */
	private static final int ZZ_LEXSTATE[] = {
			0, 0, 1, 1
	};

	/**
	 * 将字符转换为字符类的顶层表
	 */
	private static final int[] ZZ_CMAP_TOP = zzUnpackcmap_top();

	private static final String ZZ_CMAP_TOP_PACKED_0 = "\1\0\327\u0100\10\u0200\u1020\u0100";

	private static int[] zzUnpackcmap_top() {
		final int[] result = new int[4352];
		int offset = 0;
		offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
		return result;
	}

	private static int zzUnpackcmap_top(String packed, int offset, int[] result) {
		int i = 0; /* index in packed string  */
		int j = offset; /* index in unpacked array */
		final int l = packed.length();
		while (i < l) {
			int count = packed.charAt(i++);
			final int value = packed.charAt(i++);
			do
				result[j++] = value;
			while (--count > 0);
		}
		return j;
	}

	/**
	 * 将字符转换为字符类的二级表
	 */
	private static final int[] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

	private static final String ZZ_CMAP_BLOCKS_PACKED_0 = "\11\0\2\1\2\0\1\1\22\0\1\1\1\0\1\2" +
			"\10\0\1\3\1\4\1\5\1\6\1\7\12\10\1\11" +
			"\6\0\4\12\1\13\1\12\24\0\1\14\1\15\1\16" +
			"\3\0\1\17\1\20\2\12\1\21\1\22\5\0\1\23" +
			"\1\0\1\24\3\0\1\25\1\26\1\27\1\30\5\0" +
			"\1\31\1\0\1\32\u0182\0\u0100\33";

	private static int[] zzUnpackcmap_blocks() {
		final int[] result = new int[768];
		int offset = 0;
		offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
		return result;
	}

	private static int zzUnpackcmap_blocks(String packed, int offset, int[] result) {
		int i = 0; /* index in packed string  */
		int j = offset; /* index in unpacked array */
		final int l = packed.length();
		while (i < l) {
			int count = packed.charAt(i++);
			final int value = packed.charAt(i++);
			do
				result[j++] = value;
			while (--count > 0);
		}
		return j;
	}

	/**
	 * 将 DFA 状态转换为动作 switch 标签。
	 */
	private static final int[] ZZ_ACTION = zzUnpackAction();

	private static final String ZZ_ACTION_PACKED_0 = "\2\0\1\1\1\2\1\3\1\4\1\1\1\5\1\6" +
			"\1\7\1\10\3\1\1\11\1\12\1\13\1\14\1\15" +
			"\5\0\1\16\1\17\1\15\1\20\1\21\1\22\1\23" +
			"\1\24\1\0\1\5\1\0\1\5\4\0\1\25\1\26" +
			"\2\0\1\27";

	private static int[] zzUnpackAction() {
		final int[] result = new int[45];
		int offset = 0;
		offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
		return result;
	}

	private static int zzUnpackAction(String packed, int offset, int[] result) {
		int i = 0; /* index in packed string  */
		int j = offset; /* index in unpacked array */
		final int l = packed.length();
		while (i < l) {
			int count = packed.charAt(i++);
			final int value = packed.charAt(i++);
			do
				result[j++] = value;
			while (--count > 0);
		}
		return j;
	}

	/**
	 * 将状态转换为转移表中的行索引
	 */
	private static final int[] ZZ_ROWMAP = zzUnpackRowMap();

	private static final String ZZ_ROWMAP_PACKED_0 = "\0\0\0\34\0\70\0\124\0\70\0\70\0\160\0\214" +
			"\0\70\0\70\0\70\0\250\0\304\0\340\0\70\0\70" +
			"\0\374\0\70\0\u0118\0\u0134\0\u0150\0\u016c\0\u0188\0\u01a4" +
			"\0\70\0\70\0\70\0\70\0\70\0\70\0\70\0\70" +
			"\0\u01c0\0\u01dc\0\u01f8\0\u01f8\0\u0214\0\u0230\0\u024c\0\u0268" +
			"\0\70\0\70\0\u0284\0\u02a0\0\70";

	private static int[] zzUnpackRowMap() {
		final int[] result = new int[45];
		int offset = 0;
		offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
		return result;
	}

	private static int zzUnpackRowMap(String packed, int offset, int[] result) {
		int i = 0; /* index in packed string  */
		int j = offset; /* index in unpacked array */
		final int l = packed.length();
		while (i < l) {
			final int high = packed.charAt(i++) << 16;
			result[j++] = high | packed.charAt(i++);
		}
		return j;
	}

	/**
	 * DFA 的转移表
	 */
	private static final int[] ZZ_TRANS = zzUnpackTrans();

	private static final String ZZ_TRANS_PACKED_0 = "\1\3\1\4\1\5\1\3\1\6\1\7\2\3\1\10" +
			"\1\11\2\3\1\12\1\3\1\13\3\3\1\14\1\3" +
			"\1\15\2\3\1\16\1\3\1\17\1\20\1\0\2\21" +
			"\1\22\12\21\1\23\16\21\35\0\1\4\42\0\1\10" +
			"\31\0\1\24\1\0\1\10\2\0\1\25\5\0\1\25" +
			"\31\0\1\26\44\0\1\27\30\0\1\30\6\0\2\21" +
			"\1\0\12\21\1\0\16\21\2\0\1\31\4\0\1\32" +
			"\5\0\1\33\2\0\1\34\1\0\1\35\1\0\1\36" +
			"\1\37\1\0\1\40\1\41\13\0\1\42\26\0\1\43" +
			"\1\0\1\43\2\0\1\44\46\0\1\45\33\0\1\46" +
			"\40\0\1\47\13\0\1\50\1\0\2\50\3\0\4\50" +
			"\21\0\1\42\2\0\1\25\5\0\1\25\22\0\1\44" +
			"\51\0\1\47\30\0\1\51\31\0\1\52\22\0\1\53" +
			"\1\0\2\53\3\0\4\53\21\0\1\54\1\0\2\54" +
			"\3\0\4\54\21\0\1\55\1\0\2\55\3\0\4\55" +
			"\11\0";

	private static int[] zzUnpackTrans() {
		final int[] result = new int[700];
		int offset = 0;
		offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
		return result;
	}

	private static int zzUnpackTrans(String packed, int offset, int[] result) {
		int i = 0; /* index in packed string  */
		int j = offset; /* index in unpacked array */
		final int l = packed.length();
		while (i < l) {
			int count = packed.charAt(i++);
			int value = packed.charAt(i++);
			value--;
			do
				result[j++] = value;
			while (--count > 0);
		}
		return j;
	}

	/** "Unknown internal scanner error" 的错误码。 */
	private static final int ZZ_UNKNOWN_ERROR = 0;
	/** "could not match input" 的错误码。 */
	private static final int ZZ_NO_MATCH = 1;
	/** "pushback value was too large" 的错误码。 */
	private static final int ZZ_PUSHBACK_2BIG = 2;

	/**
	 * 分别对应 {@link #ZZ_UNKNOWN_ERROR}、{@link #ZZ_NO_MATCH} 和
	 * {@link #ZZ_PUSHBACK_2BIG} 的错误消息。
	 */
	private static final String ZZ_ERROR_MSG[] = {
			"Unknown internal scanner error",
			"Error: could not match input",
			"Error: pushback value was too large"
	};

	/**
	 * ZZ_ATTRIBUTE[aState] 包含状态 {@code aState} 的属性
	 */
	private static final int[] ZZ_ATTRIBUTE = zzUnpackAttribute();

	private static final String ZZ_ATTRIBUTE_PACKED_0 = "\2\0\1\11\1\1\2\11\2\1\3\11\3\1\2\11" +
			"\1\1\1\11\1\1\5\0\10\11\1\0\1\1\1\0" +
			"\1\1\4\0\2\11\2\0\1\11";

	private static int[] zzUnpackAttribute() {
		final int[] result = new int[45];
		int offset = 0;
		offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
		return result;
	}

	private static int zzUnpackAttribute(String packed, int offset, int[] result) {
		int i = 0; /* index in packed string  */
		int j = offset; /* index in unpacked array */
		final int l = packed.length();
		while (i < l) {
			int count = packed.charAt(i++);
			final int value = packed.charAt(i++);
			do
				result[j++] = value;
			while (--count > 0);
		}
		return j;
	}

	/** 输入设备。 */
	private java.io.Reader zzReader;

	/** DFA 的当前状态。 */
	private int zzState;

	/** 当前词法状态。 */
	private int zzLexicalState = YYINITIAL;

	/**
	 * 此缓冲区包含当前待匹配的文本，也是 {@link #yytext()}
	 * 字符串的来源。
	 */
	private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

	/** 上一个接受状态时的文本位置。 */
	private int zzMarkedPos;

	/** 缓冲区中的当前文本位置。 */
	private int zzCurrentPos;

	/** 标记 {@link #yytext()} 字符串在缓冲区中的起始位置。 */
	private int zzStartRead;

	/** 标记缓冲区中最后一个已从输入读取的字符。 */
	private int zzEndRead;

	/**
	 * 扫描器是否已到达文件末尾。
	 * @see #yyatEOF
	 */
	private boolean zzAtEOF;

	/**
	 * {@link #zzBuffer} 中超出 {@link #zzEndRead} 的已占用位置数。
	 *
	 * <p>当前导/高位代理项从输入流读入 {@link #zzBuffer} 的最后一个位置时，
	 * 此值为 1；否则为 0。
	 */
	private int zzFinalHighSurrogate = 0;

	/** 到匹配文本开头为止遇到的换行符数量。 */
	@SuppressWarnings("unused")
	private int yyline;

	/** 从最后一个换行符到匹配文本开头的字符数。 */
	@SuppressWarnings("unused")
	private int yycolumn;

	/** 到匹配文本开头为止的字符数。 */
	private long yychar;

	/** 扫描器当前是否位于行首。 */
	@SuppressWarnings("unused")
	private boolean zzAtBOL = true;

	/** 用户 EOF 代码是否已执行。 */
	@SuppressWarnings("unused")
	private boolean zzEOFDone;

	/* user code: */
	private StringBuilder sb = new StringBuilder();

	long getPosition() {
		return this.yychar;
	}

	/**
	 * 创建新的扫描器
	 *
	 * @param   in  用于读取输入的 java.io.Reader。
	 */
	Yylex(java.io.Reader in) {
		this.zzReader = in;
	}

	/**
	 * 将原始输入码点转换为 DFA 表的行
	 */
	private static int zzCMap(int input) {
		final int offset = input & 255;
		return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
	}

	/**
	 * 重新填充输入缓冲区。
	 *
	 * @return 当且仅当有新输入时为 {@code false}。
	 * @exception java.io.IOException  若发生任何 I/O 错误
	 */
	private boolean zzRefill() throws java.io.IOException {

		/* first: make room (if you can) */
		if (this.zzStartRead > 0) {
			this.zzEndRead += this.zzFinalHighSurrogate;
			this.zzFinalHighSurrogate = 0;
			System.arraycopy(this.zzBuffer, this.zzStartRead,
					this.zzBuffer, 0,
					this.zzEndRead - this.zzStartRead);

			/* translate stored positions */
			this.zzEndRead -= this.zzStartRead;
			this.zzCurrentPos -= this.zzStartRead;
			this.zzMarkedPos -= this.zzStartRead;
			this.zzStartRead = 0;
		}

		/* is the buffer big enough? */
		if (this.zzCurrentPos >= this.zzBuffer.length - this.zzFinalHighSurrogate) {
			/* if not: blow it up */
			final char newBuffer[] = new char[this.zzBuffer.length * 2];
			System.arraycopy(this.zzBuffer, 0, newBuffer, 0, this.zzBuffer.length);
			this.zzBuffer = newBuffer;
			this.zzEndRead += this.zzFinalHighSurrogate;
			this.zzFinalHighSurrogate = 0;
		}

		/* fill the buffer with new input */
		final int requested = this.zzBuffer.length - this.zzEndRead;
		final int numRead = this.zzReader.read(this.zzBuffer, this.zzEndRead, requested);

		/* not supposed to occur according to specification of java.io.Reader */
		if (numRead == 0)
			throw new java.io.IOException(
					"Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
		if (numRead > 0) {
			this.zzEndRead += numRead;
			if (Character.isHighSurrogate(this.zzBuffer[this.zzEndRead - 1]))
				if (numRead == requested) { // We requested too few chars to encode a full Unicode character
					--this.zzEndRead;
					this.zzFinalHighSurrogate = 1;
				} else { // There is room in the buffer for at least one more char
					final int c = this.zzReader.read(); // Expecting to read a paired low surrogate char
					if (c == -1)
						return true;
					else
						this.zzBuffer[this.zzEndRead++] = (char) c;
				}
			/* potentially more input available */
			return false;
		}

		/* numRead < 0 ==> end of stream */
		return true;
	}

	/**
	 * 关闭输入读取器。
	 *
	 * @throws java.io.IOException 若读取器无法关闭。
	 */
	public final void yyclose() throws java.io.IOException {
		this.zzAtEOF = true; // indicate end of file
		this.zzEndRead = this.zzStartRead; // invalidate buffer

		if (this.zzReader != null)
			this.zzReader.close();
	}

	/**
	 * 重置扫描器，使其从新的输入流读取。
	 *
	 * <p>不会关闭旧的读取器。
	 *
	 * <p>所有内部变量都会被重置，旧的输入流<b>不能</b>再被复用（内部
	 * 缓冲区会被丢弃）。词法状态设为 {@code ZZ_INITIAL}。
	 *
	 * <p>如果内部扫描缓冲区曾经增长，会被缩回其初始长度。
	 *
	 * @param reader 新的输入流。
	 */
	public final void yyreset(java.io.Reader reader) {
		this.zzReader = reader;
		this.zzEOFDone = false;
		this.yyResetPosition();
		this.zzLexicalState = YYINITIAL;
		if (this.zzBuffer.length > ZZ_BUFFERSIZE)
			this.zzBuffer = new char[ZZ_BUFFERSIZE];
	}

	/**
	 * 重置输入位置。
	 */
	private final void yyResetPosition() {
		this.zzAtBOL = true;
		this.zzAtEOF = false;
		this.zzCurrentPos = 0;
		this.zzMarkedPos = 0;
		this.zzStartRead = 0;
		this.zzEndRead = 0;
		this.zzFinalHighSurrogate = 0;
		this.yyline = 0;
		this.yycolumn = 0;
		this.yychar = 0L;
	}

	/**
	 * 返回扫描器是否已到达其读取器的末尾。
	 *
	 * @return 扫描器是否已到达 EOF。
	 */
	public final boolean yyatEOF() {
		return this.zzAtEOF;
	}

	/**
	 * 返回当前词法状态。
	 *
	 * @return 当前词法状态。
	 */
	public final int yystate() {
		return this.zzLexicalState;
	}

	/**
	 * 进入新的词法状态。
	 *
	 * @param newState 新的词法状态
	 */
	public final void yybegin(int newState) {
		this.zzLexicalState = newState;
	}

	/**
	 * 返回当前正则表达式匹配到的文本。
	 *
	 * @return 匹配到的文本。
	 */
	public final String yytext() {
		return new String(this.zzBuffer, this.zzStartRead, this.zzMarkedPos - this.zzStartRead);
	}

	/**
	 * 返回匹配文本中给定位置的字符。
	 *
	 * <p>等价于 {@code yytext().charAt(pos)}，但更快。
	 *
	 * @param position 要获取的字符的位置。取值范围为 0 到 {@code yylength()-1}。
	 *
	 * @return 位于 {@code position} 的字符。
	 */
	public final char yycharat(int position) {
		return this.zzBuffer[this.zzStartRead + position];
	}

	/**
	 * 匹配到的字符数。
	 *
	 * @return 匹配文本区域的长度。
	 */
	public final int yylength() {
		return this.zzMarkedPos - this.zzStartRead;
	}

	/**
	 * 报告扫描过程中发生的错误。
	 *
	 * <p>在结构良好的扫描器中（不使用或只正确使用 {@code yypushback(int)}，并有
	 * 匹配全部的回退规则），只有在
	 * "不可能发生" 的情况下才会调用此方法。
	 *
	 * <p>如果调用了此方法，说明出现了严重问题（例如 JFlex 的 bug 生成了有缺陷的
	 * 扫描器等）。
	 *
	 * <p>常规的语法/扫描器级别错误处理应在错误回退规则中完成。
	 *
	 * @param errorCode 要显示的错误消息的代码。
	 */
	private static void zzScanError(int errorCode) {
		String message;
		try {
			message = ZZ_ERROR_MSG[errorCode];
		} catch (final ArrayIndexOutOfBoundsException e) {
			message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
		}

		throw new Error(message);
	}

	/**
	 * 将指定数量的字符推回输入流。
	 *
	 * <p>它们会在下一次调用扫描方法时被再次读取。
	 *
	 * @param number 要再次读取的字符数。
	 */
	public void yypushback(int number) {
		if (number > this.yylength())
			zzScanError(ZZ_PUSHBACK_2BIG);

		this.zzMarkedPos -= number;
	}

	/**
	 * 继续扫描，直到匹配到下一个正则表达式、遇到输入结束
	 * 或发生 I/O 错误。
	 *
	 * @return 下一个记号。
	 * @throws JSONParseException 若发生任何 I/O 错误。
	 * @throws java.io.IOException
	 */
	public Yytoken yylex() throws java.io.IOException, JSONParseException {
		int zzInput;
		int zzAction;

		// cached fields:
		int zzCurrentPosL;
		int zzMarkedPosL;
		int zzEndReadL = this.zzEndRead;
		char[] zzBufferL = this.zzBuffer;

		final int[] zzTransL = ZZ_TRANS;
		final int[] zzRowMapL = ZZ_ROWMAP;
		final int[] zzAttrL = ZZ_ATTRIBUTE;

		while (true) {
			zzMarkedPosL = this.zzMarkedPos;

			this.yychar += zzMarkedPosL - this.zzStartRead;

			zzAction = -1;

			zzCurrentPosL = this.zzCurrentPos = this.zzStartRead = zzMarkedPosL;

			this.zzState = ZZ_LEXSTATE[this.zzLexicalState];

			// set up zzAction for empty match case:
			int zzAttributes = zzAttrL[this.zzState];
			if ((zzAttributes & 1) == 1)
				zzAction = this.zzState;

			zzForAction:
			{
				while (true) {

					if (zzCurrentPosL < zzEndReadL) {
						zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
						zzCurrentPosL += Character.charCount(zzInput);
					} else if (this.zzAtEOF) {
						zzInput = YYEOF;
						break zzForAction;
					} else {
						// store back cached positions
						this.zzCurrentPos = zzCurrentPosL;
						this.zzMarkedPos = zzMarkedPosL;
						final boolean eof = this.zzRefill();
						// get translated positions and possibly new buffer
						zzCurrentPosL = this.zzCurrentPos;
						zzMarkedPosL = this.zzMarkedPos;
						zzBufferL = this.zzBuffer;
						zzEndReadL = this.zzEndRead;
						if (eof) {
							zzInput = YYEOF;
							break zzForAction;
						} else {
							zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
							zzCurrentPosL += Character.charCount(zzInput);
						}
					}
					final int zzNext = zzTransL[zzRowMapL[this.zzState] + zzCMap(zzInput)];
					if (zzNext == -1)
						break zzForAction;
					this.zzState = zzNext;

					zzAttributes = zzAttrL[this.zzState];
					if ((zzAttributes & 1) == 1) {
						zzAction = this.zzState;
						zzMarkedPosL = zzCurrentPosL;
						if ((zzAttributes & 8) == 8)
							break zzForAction;
					}

				}
			}

			// store back cached position
			this.zzMarkedPos = zzMarkedPosL;

			if (zzInput == YYEOF && this.zzStartRead == this.zzCurrentPos) {
				this.zzAtEOF = true;
				return null;
			} else
				switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
					case 1: {
						throw new JSONParseException(this.yychar, JSONParseException.Problems.UNEXPECTED_CHARACTER, String.valueOf(this.yycharat(0)));
					}
					// fall through
					case 24:
						break;
					case 2: {
					}
					// fall through
					case 25:
						break;
					case 3: {
						this.sb = null;
						this.sb = new StringBuilder();
						this.yybegin(STRING_BEGIN);
					}
					// fall through
					case 26:
						break;
					case 4: {
						return new Yytoken(Yytoken.Types.COMMA, null);
					}
					// fall through
					case 27:
						break;
					case 5: {
						final java.math.BigDecimal val = new java.math.BigDecimal(this.yytext());
						return new Yytoken(Yytoken.Types.DATUM, val);
					}
					// fall through
					case 28:
						break;
					case 6: {
						return new Yytoken(Yytoken.Types.COLON, null);
					}
					// fall through
					case 29:
						break;
					case 7: {
						return new Yytoken(Yytoken.Types.LEFT_SQUARE, null);
					}
					// fall through
					case 30:
						break;
					case 8: {
						return new Yytoken(Yytoken.Types.RIGHT_SQUARE, null);
					}
					// fall through
					case 31:
						break;
					case 9: {
						return new Yytoken(Yytoken.Types.LEFT_BRACE, null);
					}
					// fall through
					case 32:
						break;
					case 10: {
						return new Yytoken(Yytoken.Types.RIGHT_BRACE, null);
					}
					// fall through
					case 33:
						break;
					case 11: {
						this.sb.append(this.yytext());
					}
					// fall through
					case 34:
						break;
					case 12: {
						this.yybegin(YYINITIAL);
						return new Yytoken(Yytoken.Types.DATUM, this.sb.toString());
					}
					// fall through
					case 35:
						break;
					case 13: {
						this.sb.append('\\');
					}
					// fall through
					case 36:
						break;
					case 14: {
						this.sb.append('"');
					}
					// fall through
					case 37:
						break;
					case 15: {
						this.sb.append('/');
					}
					// fall through
					case 38:
						break;
					case 16: {
						this.sb.append('\b');
					}
					// fall through
					case 39:
						break;
					case 17: {
						this.sb.append('\f');
					}
					// fall through
					case 40:
						break;
					case 18: {
						this.sb.append('\n');
					}
					// fall through
					case 41:
						break;
					case 19: {
						this.sb.append('\r');
					}
					// fall through
					case 42:
						break;
					case 20: {
						this.sb.append('\t');
					}
					// fall through
					case 43:
						break;
					case 21: {
						return new Yytoken(Yytoken.Types.DATUM, null);
					}
					// fall through
					case 44:
						break;
					case 22: {
						final Boolean val = Boolean.valueOf(this.yytext());
						return new Yytoken(Yytoken.Types.DATUM, val);
					}
					// fall through
					case 45:
						break;
					case 23: {
						try {
							final int ch = Integer.parseInt(this.yytext().substring(2), 16);
							this.sb.append((char) ch);
						} catch (final Exception e) {
							/* The lexer is broken if it can build a 4 byte character code and fail to append the character. */
							throw new JSONParseException(this.yychar, JSONParseException.Problems.UNEXPECTED_EXCEPTION, e);
						}
					}
					// fall through
					case 46:
						break;
					default:
						zzScanError(ZZ_NO_MATCH);
				}
		}
	}

}
